src/web/basics/button/button.js, src/web/basics/button/tests/tests-button.html, webpack.config.js
@recyclerobot take a look at this PR plz
=> change libraryTarget to UMD and fix setTitle/setLink bug

src/interface/interface.json
=> Add GlobalNav.SubNav.Tabs to interface.json

src/web/basics/button/button.js
=> Have button setTitle update "title" attribute

src/interface/interface.json
=> Add GlobalNav.Avatar to interface.json

plopfile.js, src/web/components/global-nav/top-nav/shortcut/shortcut.html, src/web/components/global-nav/top-nav/shortcut/shortcut.js, src/web/components/global-nav/top-nav/shortcut/shortcut.scss, src/web/components/global-nav/top-nav/shortcut/tests/gemini-shortcut.html, src/web/components/global-nav/top-nav/shortcut/tests/tests-shortcut.html, src/web/helpers/skeletons/skeleton-gemini-template.html, src/web/helpers/skeletons/skeleton-tests-template.html, src/web/helpers/test.js
This is a first pass at a shortcut - before I do any more I want to make sure I understand what's required.
* Included a "help" svg in icons (possibly temporary)
* interface, css, template, js, etc.
* test-shortcut.html
* little bit of refactoring in topnav.js
* export some stuff into a helpers/test.js for use in the test files.
* add test templates to plopfile.js
=> [DNM] For review: Features/shortcut component

src/web/components/global-nav/side-nav/section/group/module/submodule/submodule.html
This sets the hide class on submodules rather than having it on module.
=> remove class from module add to submodule

src/interface/interface.json, src/web/components/global-nav/tests/tests-global-nav.html
Two changes:
1. interface.json had to have some updates to get TopNav Search working
1. the Module/Submodule changes hadn't made it into one of the global nav tests.
=> add global nav tests and update the topnav search events interface.

deploy/deploy-dev.sh
small fix to allow deploying static build to S3 from a specific branch
=> update to deploy shell script

.vscode/settings.json, src/web/basics/button/button.html, src/web/basics/button/button.js, src/web/basics/button/button.scss, src/web/basics/button/tests/tests-button.html, src/web/basics/icon-button/icon-button.html, src/web/basics/icon-button/icon-button.js, src/web/basics/icon-button/icon-button.scss, src/web/components/global-nav/tests/tests-global-nav.html
=> Disabled IconButtons do not trigger events

index.html
generate updated index.html page for github pages.
=> add updated index.html

src/web/basics/form-elements/text-field/text-field.scss, src/web/index.js
- Add TextFIeld to `index.js`
- Order Components in `index.js` alphabetically
- Touch up CSS for TextField after finding some conflicts w/ Orion playground css
=> Add TextField to index.js

src/web/basics/form-elements/text-field/tests/tests-text-field.html, src/web/basics/form-elements/text-field/text-field.html, src/web/basics/form-elements/text-field/text-field.js, src/web/basics/form-elements/text-field/text-field.scss
show and hide label, but always keep it in the markup, so we can set label and name in any order.
=> TextField label is always rendered

src/web/basics/form-elements/checkbox/checkbox.html, src/web/basics/form-elements/input-button/input-button.scss, src/web/basics/form-elements/radio-button/radio-button.html, src/web/components/global-nav/global-nav.scss, src/web/helpers/css/mixins/states.scss
Somehow the hidden class stopped being added for a blank label. This fixes that.
=> put back hidden class

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/rollup.config.js, src/implementations/react/src/adapters/FormElements/PasswordFieldAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.story.js, src/implementations/react/src/adapters/SpacerAdapter.test.js, src/implementations/react/src/adapters/__snapshots__/SpacerAdapter.test.js.snap, src/implementations/react/src/playground/index.css, src/implementations/react/src/playground/index.js, src/implementations/react/src/playground/sections/SpacerSection.js, src/implementations/react/src/react-hig.js, src/implementations/react/src/stories/index.js, src/implementations/vanilla/package.json
#211 Add SpacingAdapter
* adapter
* docgeninfo
* proptypes
* playground
* story
* unit tests
This also has updates to package.json(s) to get rid of some warnings and error messages
=> SpacerAdapter

src/implementations/react/src/adapters/FormElements/CheckboxAdapter.js, src/implementations/react/src/adapters/FormElements/PasswordFieldAdapter.js, src/implementations/react/src/adapters/FormElements/RadioButtonAdapter.js, src/implementations/react/src/adapters/FormElements/RangeAdapter.js, src/implementations/react/src/adapters/FormElements/TextAreaAdapter.js, src/implementations/react/src/adapters/FormElements/TextFieldAdapter.js, src/implementations/vanilla/src/basics/form-elements/text-area/tests/tests-text-area.html
Additional events and props needed to be included in componentDidMount  for some adapters.  
I did this slightly differently from the way @nfiniteset  was doing it; let me know if it's ok.
=> add missing updates to some adapters

src/implementations/react/src/adapters/TextLinkAdapter.js, src/implementations/react/src/adapters/TextLinkAdapter.test.js, src/implementations/react/src/adapters/__snapshots__/TextLinkAdapter.test.js.snap, src/implementations/react/src/playground/index.js, src/implementations/react/src/playground/sections/TextLinkSection.js, src/implementations/react/src/react-hig.js, src/implementations/react/src/stories/TextLink.story.js, src/implementations/react/src/stories/index.js, src/implementations/vanilla/src/basics/text-link/text-link.html, src/implementations/vanilla/src/basics/text-link/text-link.scss
Story: https://github.com/Autodesk/hig/issues/282
Adds TextLink adapter/component.  Includes corresponding unit test and playground/storybook entries
Paired with @aneyzberg
=> React TextLink adapter

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/elements/components/GlobalNav/GlobalNav.js, src/implementations/react/src/elements/components/RichText.js, src/implementations/react/src/hig-react.js, src/implementations/react/src/playground/sections/SpacerSection.js
- Wrap GlobalNav content in a div
- Append proper Slot to SpacerAdapter in playground
- Don’t needlessly rename exports from hig-react.js
- Pass either chidren or innerHtml to RichText, not both
=> Fix many console errors

.circleci/config.yml, src/implementations/react/package.json, src/implementations/react/scripts/validate-version.js
Adds *validate* CircleCI check to pull requests.  This includes checking that the package.json "version" property does not equal that of the *hig-react* npm module in github master
=> Add CircleCI test task to confirm incremented hig-react version

.circleci/config.yml
See: https://github.com/Autodesk/hig/pull/325
=> Exclude running hig-react version check on master

.circleci/config.yml
* Explicit paths for package.json checksums
* Comments
* Share default settings across jobs
=> CircleCI configuration improvements

src/implementations/react/package.json
This is a dummy branch that contains a hig-react version bump (0.22.2) and git tag.  Merging this into master will test the auto-deploy job
=> Dummy branch with version bump and tag to test hig-react auto-deploy job

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/adapters/SpacerAdapter.js, src/implementations/react/src/elements/components/GlobalNav/GlobalNav.js, src/implementations/react/src/elements/components/Spacer.js, src/implementations/react/src/hig-react.js, src/implementations/react/src/playground/index.js, src/implementations/react/src/playground/sections/SpacerSection.js, src/implementations/vanilla/src/basics/responsive/responsive.js, src/implementations/vanilla/src/basics/responsive/responsive.scss, src/implementations/vanilla/src/index.js
- Enable finer control of side nav open state so website can close menu after navigation on mobile.
ALSO fixes a bug in the Spacer component.
=> Enable finer control over SideNav open state

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/elements/components/GlobalNav/SideNav/WithState.js
Not tested 😬. This component is hard to test right now. Will keep in mind for cleanup work in a couple of weeks.
=> Activate submodule when clicking module

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/adapters/GridAdapter.js
=> Enable removing GridAdapter children

src/implementations/react/src/elements/components/FormElements/Checkbox.js, src/implementations/react/src/elements/components/FormElements/PasswordField.js, src/implementations/react/src/elements/components/FormElements/Range.js, src/implementations/react/src/elements/components/FormElements/TextArea.js, src/implementations/react/src/elements/components/Typography.js
Includes:
* [Checkbox](https://github.com/Autodesk/hig/pull/377)
* [PasswordField](https://github.com/Autodesk/hig/pull/375)
* [Range](https://github.com/Autodesk/hig/pull/371)
* [Textarea](https://github.com/Autodesk/hig/pull/374)
* [Typograpghy](https://github.com/Autodesk/hig/pull/370)
=> Improved docgen

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/adapters/SlotCellAdapter.js, src/implementations/react/src/adapters/SlotHeadCellAdapter.js, src/implementations/react/src/adapters/TableRowAdapter.js, src/implementations/react/src/elements/components/FormElements/Checkbox.js, src/implementations/react/src/elements/components/FormElements/HeaderCheckbox.js, src/implementations/react/src/elements/components/FormElements/RowCheckbox.js, src/implementations/react/src/elements/components/SelectableTable.js, src/implementations/react/src/elements/components/SelectableTable.test.js, src/implementations/react/src/elements/components/SlotHeadCell.js, src/implementations/react/src/elements/components/Table.js, src/implementations/react/src/hig-react.js, src/implementations/react/src/playground/index.js, src/implementations/react/src/playground/sections/IconSection.js, src/implementations/react/src/playground/sections/SelectableTableSection.js, src/implementations/react/src/playground/sections/TableSection.js, src/implementations/vanilla/src/basics/form-elements/checkbox/checkbox.scss, src/implementations/vanilla/src/components/table/table-head/slot-head-cell/slot-head-cell.js, src/implementations/vanilla/src/components/table/table-head/slot-head-cell/slot-head-cell.scss, src/implementations/vanilla/src/components/table/table-head/table-head.scss, src/implementations/vanilla/src/components/table/table-head/text-head-cell/text-head-cell.scss, src/implementations/vanilla/src/components/table/table-row/icon-cell/icon-cell.scss, src/implementations/vanilla/src/components/table/table-row/slot-cell/slot-cell.js, src/implementations/vanilla/src/components/table/table-row/slot-cell/slot-cell.scss, src/implementations/vanilla/src/components/table/table-row/table-row.js, src/implementations/vanilla/src/components/table/table-row/table-row.scss, src/implementations/vanilla/src/components/table/table.scss, src/implementations/vanilla/src/index.js, src/interface/interface.json
=> Enable selecting rows in table

.circleci/config.yml, README.md, src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/scripts/validate-version.js, src/implementations/vanilla/README.md
v0.28.6
- Add readme fixes
- Test modified deploy process
=> Deploy v0.28.6

src/implementations/react/src/playground/index.js, src/implementations/vanilla/src/components/global-nav/side-nav/side-nav.js, src/implementations/vanilla/src/components/global-nav/side-nav/side-nav.scss
Implements #427 
**From this:**
**To this:**
=> Style header links

packages/interface/package.json, packages/react/package.json, packages/vanilla/package.json
- hig-interface@0.1.4
- hig-react@0.28.11
- hig-vanilla@0.1.4
=> Publish updated versions

packages/react/src/hig-react.js, packages/react/src/hig-react.test.js, packages/vanilla/.eslintrc.js, packages/vanilla/src/basics/colors/colors.js, packages/vanilla/src/index.js
Fix: Colors and sizes were not being exported. They are now.
---
Adds tests to ensure colors, sizes, and breakpoints are exported from hig-react.
=> Export colors

packages/react/DEVELOPING.md, packages/react/README.md, packages/vanilla/DEVELOPING.md, packages/vanilla/README.md, packages/vanilla/package.json
Addresses https://github.com/Autodesk/hig/issues/525.
1. I recommend `webpack-dev-server` for faster previewing of `hig-vanilla` changes.
2. Document the Lerna-backed process for developing `hig-react` when relying on local `hig-vanilla` changes.
=> Chores: documenting developer setup

packages/react/src/elements/components/GlobalNav/SideNav/WithState.js
Addresses https://github.com/Autodesk/hig/issues/542
When a module has 5 or fewer submodules...
1. Its default state is expanded.
2. Clicking the module link focuses the first submodule, and does not change the minimization.
3. The Collapse arrow still allows you to minimize/expand.
When a module has 6 or more submodules, the existing behavior applies...
1. Its default state is minimized.
2. Clicking the module link focuses the first submodule, *and* expands the module.
3. The Collapse arrow still allows you to minimize/expand.
=> Features: [SideNav] Keep modules with 5 or fewer submodules expanded

.circleci/config.yml, packages/interface/interface.json, packages/react/src/adapters/GlobalNav/TopNav/TopNavAdapter.js, packages/react/src/playground/index.js, packages/vanilla/package.json, packages/vanilla/src/components/global-nav/top-nav/top-nav.html, packages/vanilla/src/components/global-nav/top-nav/top-nav.js, packages/vanilla/src/components/global-nav/top-nav/top-nav.scss
Add a prop to allow hiding the hamburger menu icon. This combines well with the current `sideNavOpen` prop if you want to force the sidenav to always be open.
=> [GlobalNav] Allow hiding the hamburger menu icon in TopNav

packages/interface/interface.json, packages/react/src/adapters/GlobalNav/TopNav/NotificationsAdapter.js, packages/react/src/adapters/GlobalNav/TopNav/NotificationsAdapter.test.js, packages/react/src/elements/components/GlobalNav/TopNav/Notifications.js, packages/vanilla/src/components/global-nav/top-nav/notifications/_list/_list.html, packages/vanilla/src/components/global-nav/top-nav/notifications/_list/_list.js, packages/vanilla/src/components/global-nav/top-nav/notifications/_list/_list.scss, packages/vanilla/src/components/global-nav/top-nav/notifications/notification/notification.scss, packages/vanilla/src/components/global-nav/top-nav/notifications/notifications.js
=> [Notifications] Keep title fixed above list of notifications

packages/react/src/playground/index.js
=> Use examples from the Sketch file

packages/interface/interface.json, packages/react/src/playground/index.js, packages/react/src/playground/sections/NotificationsSection.js, packages/vanilla/src/components/global-nav/top-nav/shortcut/shortcut.html, packages/vanilla/src/components/global-nav/top-nav/shortcut/shortcut.js
Revive the Notifications section to demonstrate the interface in isolation.
=> Standalone Notifications example

packages/react/src/elements/components/GlobalNav/TopNav/Notification.js, packages/react/src/elements/components/GlobalNav/TopNav/Notifications.js, packages/react/src/elements/components/GlobalNav/TopNav/Notifications.test.js, packages/react/src/playground/index.js, packages/react/src/playground/sections/NotificationsSection.js
Addresses https://github.com/Autodesk/hig/issues/635.
=> Features: Featured notification element

packages/react/src/adapters/FormElements/OptionAdapter.js, packages/react/src/playground/index.js, packages/vanilla/src/basics/form-elements/option/option.html, packages/vanilla/src/basics/form-elements/option/option.js
This begins to build support in for allowing custom rendering of search results.
=> Features/Options (Search results) with custom labels

packages/react/src/elements/components/GlobalNav/SideNav/WithState.js, packages/react/src/playground/fixtures/sideNavFixtures.js
Recognizes initial `minimized` state for each module.
=> Features: [SideNav] Configurable expanded/collapsed state

packages/react/src/elements/components/GlobalNav/SideNav/Search.js, packages/react/src/elements/components/GlobalNav/TopNav/Search.js, packages/react/src/playground/index.js, packages/react/src/playground/sections/TextFieldSection.js, packages/vanilla/src/basics/form-elements/text-field/text-field.scss
Updates the playground to demonstrate proper clear buttons for TopNav search, SideNav search, and TextField.
=> Ensure Clear button consistency

package.json, packages/react/.gitignore, packages/react/.storybook/addons.js, packages/react/.storybook/config.js, packages/react/package.json, packages/react/stories/Button.js, packages/react/stories/Typography.js, packages/react/yarn.lock, packages/vanilla/package.json, packages/vanilla/src/basics/icons/icons.js, packages/vanilla/src/index.js
1. Add back Storybook
2. Add scripts to build storybook for deploy
3. Automatically read new stories from `stories/` directory
4. Automatically enhance all stories with docgenInfo
5. Write stories for Button and Typography
=> Features: Reintroduce Storybook

packages/react/src/elements/components/Banner/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap, packages/react/src/elements/components/IconButton/__snapshots__/IconButton.test.js.snap, packages/react/src/elements/components/Notification/__snapshots__/Notification.test.js.snap, packages/react/src/elements/components/Shortcut/__snapshots__/Shortcut.test.js.snap
Follow-up to https://github.com/Autodesk/hig/pull/814.
=> Bugfixes: Update snapshots for components using IconButton

packages/banner/src/__stories__/Banner.stories.js, packages/storybook/utils.js
=> docs(banner): Clean up organization of knobs

packages/banner/src/__stories__/Banner.stories.js, packages/banner/src/__stories__/i18n/de.json, packages/banner/src/__stories__/i18n/en.json, packages/banner/src/__stories__/i18n/index.js, packages/banner/src/__stories__/i18n/ja.json, packages/storybook/.storybook/shared/webpack.config.js, packages/storybook/package.json, packages/storybook/utils/index.js, packages/storybook/utils/makeSelectOptions.js, packages/storybook/utils/translate.js
I had to refactor the Banner stories file in order for the source code to appear correctly. 
The internationalization example itself could be refactored when we add the next example. Just need to get this up there for today.
=> Add banner intl story 809

packages/icon-button/src/__stories__/IconButton.stories.js, packages/icon/src/__stories__/Icon.stories.js
=> docs: Fix stories for `Icon` and `IconButton`

packages/icon-button/src/icon-button.scss
Addresses https://github.com/Autodesk/hig/issues/862
Moving forward, I assume we're having Lerna update the package versions when we're ready to deploy?
=> [IconButton] Add cursor: pointer

CONTRIBUTING.md, README.md, packages/project-account-switcher/README.md, packages/table/README.md, packages/timestamp/README.md, packages/top-nav/README.md
- Add current core contributors
- Add getting started to main README
- Add links to component README from main one
- Improve descriptions of a few components
=> Revamp docs

packages/step-indicator/README.md
=> Add initial readme for Step Indicator

README.md
Add css to basic usage example.
=> Touch up docs

packages/table/package.json, packages/table/src/GridTable.js, packages/table/src/Table.js, packages/table/src/Table.test.js, yarn.lock
Reverting #937 to return to a green build. Since the dependencies changed, CircleCI is having difficulty saving the dependency cache:
```
Creating cache archive...
Uploading cache archive...
Error uploading archive: MetadataTooLarge: Your metadata headers exceed the maximum allowed metadata size
status code: 400, request id: 46198A85C6D4ABC5, host id: BSQiUjWh6wscexjHdV158guhM6pStE3c1CMjEDEThrtMdiPY+QH0VsdOY2hIulrrJwwx15BXoGc=
```
=> Revert "Merge pull request #937 from nihgwu/neo/fix-table-deps"

packages/table/package.json, packages/table/src/GridTable.js, packages/table/src/Table.js, packages/table/src/Table.test.js, yarn.lock
the initial PR was reverted, so another try here
=> fix(table): upgrade react-virtualized to use public methods for getSize

packages/flyout/README.md, packages/flyout/package.json, packages/flyout/src/Flyout.js, packages/flyout/src/Flyout.test.js, packages/flyout/src/FlyoutPresenter/FlyoutPresenter.js, packages/flyout/src/FlyoutPresenter/FlyoutPresenter.test.js, packages/flyout/src/FlyoutPresenter/__snapshots__/FlyoutPresenter.test.js.snap, packages/flyout/src/FlyoutPresenter/flyout.scss, packages/flyout/src/FlyoutPresenter/index.js, packages/flyout/src/FlyoutPresenter/index.test.js, packages/flyout/src/FlyoutPresenter/tokens.scss, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/__stories__/renderStory.js, packages/flyout/src/__stories__/stories.js, packages/flyout/src/flyout.scss, packages/flyout/src/getFlyoutPosition.js, packages/flyout/src/getFlyoutPosition.test.js, packages/flyout/src/index.js, yarn.lock
* **BREAKING DESIGN CHANGE**
- Increased padding of the flyout panel from `10px` to `12px` to standardize spacing
* Improvements
- Removed `hig-react` dependency
- Improved positioning functionality
- More consistent transition behavior
* Chores
- Transition `@hig/flyout` to the stable phase
* [Storybook](https://hig-feat-flyout.surge.sh/?selectedKind=Flyout)
* Issue #954
=> Feature: Flyout rewrite

CONTRIBUTING.md, DEVELOPING.md, docs/contribution-example/README.md, docs/contribution-example/package.json, docs/contribution-example/src/index.js, docs/contribution-example/src/index.test.js, package.json, yarn.lock
* Updated the Developing guide.
* Added `docs/contribution-example` to serve as an example package for contributions.
* Added a script to generate table of contents for documentation (`yarn run docs`).
=> Docs: Development update

packages/banner/src/__stories__/Banner.stories.js, packages/checkbox/src/__stories__/Checkbox.stories.js, packages/dropdown/src/__stories__/Dropdown.stories.js, packages/icon/src/__stories__/Icon.stories.js, packages/notifications-flyout/src/__stories__/Notification.stories.js, packages/notifications-flyout/src/__stories__/NotificationsFlyout.stories.js, packages/notifications-toast/src/__stories__/NotificationsToast.stories.js, packages/notifications-toast/src/__stories__/NotificationsToastList.stories.js, packages/profile-flyout/src/__stories__/ProfileFlyout.stories.js, packages/project-account-switcher/src/__stories__/ProjectAccountSwitcher.stories.js, packages/radio-button/src/__stories__/RadioButton.stories.js, packages/rich-text/src/__stories__/RichText.stories.js, packages/side-nav/src/__stories__/SideNav.stories.js, packages/side-nav/src/__stories__/SideNavCompact.stories.js, packages/side-nav/src/__stories__/SideNavContainer.stories.js, packages/side-nav/src/__stories__/SideNavSkeleton.stories.js, packages/side-nav/src/__stories__/SideNavSubcomponents.stories.js, packages/slider/src/__stories__/Slider.stories.js, packages/storybook/.storybook/shared/config.js, packages/text-area/src/__stories__/TextArea.stories.js, packages/text-field/src/__stories__/TextField.stories.js, packages/themes/src/__stories__/ThemeContext.stories.js, packages/top-nav/src/__stories__/TopNav.stories.js, packages/typography/src/__stories__/Typography.stories.js
Who knew storybook had a third level of categorization? Weird API, but I'll take it.
=> Group stories by category the by component

packages/side-nav/src/Module/presenters/module.scss
=> Fix: Add a pointer cursor to SideNav.Module

packages/tabs/src/Tabs.js, packages/tabs/src/__snapshots__/Tabs.test.js.snap
=> fix(behavior): remove invalid prop from Fragment

packages/themes/CHANGELOG.md, packages/themes/package.json
=> Release: July 19, 2018

packages/top-nav/README.md, packages/top-nav/src/__stories__/TopNav.stories.js, packages/top-nav/src/__stories__/infoOptions.js
Story: https://github.com/Autodesk/hig/issues/1063
TopNav README is disabled. This branch enables it and revises the usage example
http://whispering-machine.surge.sh/
=> Enable README on TopNav Storybook

packages/dropdown/src/presenters/InputPresenter.test.js, packages/dropdown/src/presenters/MenuPresenter.test.js, packages/dropdown/src/presenters/OptionPresenter.test.js, packages/dropdown/src/presenters/WrapperPresenter.test.js, packages/dropdown/src/presenters/__snapshots__/InputPresenter.test.js.snap, packages/dropdown/src/presenters/__snapshots__/MenuPresenter.test.js.snap, packages/dropdown/src/presenters/__snapshots__/OptionPresenter.test.js.snap, packages/dropdown/src/presenters/__snapshots__/WrapperPresenter.test.js.snap
Issue: https://github.com/Autodesk/hig/issues/1075
As preparation for adding the feature of custom Dropdown option rendering, this branch adds markup snapshot tests for dropdown presenters
=> Markup snapshots for Dropdown presenters

.gitignore
=> chore(jetbrains): Ignore .idea directory for Jetbrains IDEs

packages/flyout/src/Flyout.js, packages/flyout/src/Flyout.test.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/__stories__/getKnobs.js, packages/flyout/src/index.js, packages/flyout/src/index.test.js, packages/flyout/src/presenters/PanelContainerPresenter.js, packages/flyout/src/presenters/__snapshots__/PanelContainerPresenter.test.js.snap, packages/storybook/utils/controlledNumber.js, packages/storybook/utils/index.js
* Correct controlled component behavior for the `open` prop
* Add `onOpen` and `onClose` props
* Add `controlledNumber` knob utility
http://hig-feat-flyout-open-handlers.surge.sh/
=> feat: correct flyout controlled behavior

packages/scripts/bin/lint.sh
- so that we can pass --fix for easy lint fixes
=> fix(lint): Pass through options to lint script

packages/flyout/src/Flyout.js, packages/flyout/src/Flyout.test.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/tooltip/src/Tooltip.js
Add `defaultOpen` prop to support uncontrolled flyout's that are open by default.
=> Feature: uncontrolled Flyout open by default

packages/flyout/src/Flyout.js, packages/flyout/src/index.js, packages/flyout/src/index.test.js, packages/notifications-flyout/src/NotificationsFlyout.js, packages/notifications-flyout/src/Panel.js, packages/notifications-flyout/src/behaviors/PanelBehavior.js
Addresses https://github.com/Autodesk/hig/issues/1201
=> fix:  max-height calc on notifications-flyout

packages/tabs/package.json, packages/tabs/src/Tab.js, packages/tabs/src/Tabs.js, packages/tabs/src/__snapshots__/Tabs.test.js.snap, packages/tabs/src/presenters/TabPresenter.js, packages/tabs/src/presenters/TabPresenter.test.js, packages/tabs/src/presenters/__snapshots__/TabPresenter.test.js.snap
> This is a feature branch PR working towards the removal of legacy packages. It is expected that this branch will fail CI.
Adds missing keyboard interactions to tab items for improved a11y.
Contributes to #1208
=> Fix: add missing keyboard interactions to Tabs

packages/banner/src/BannerAnimator/BannerAnimator.js, packages/button/src/Button.test.js, packages/checkbox/src/__gemini__/CheckboxPresenter.stories-test.js, packages/eslint-config/index.js, packages/eslint-config/package.json, packages/flyout/src/Flyout.js, packages/modal/src/__gemini__/ModalPresenter.stories-test.js, packages/modal/src/presenters/ModalPresenter.js, packages/notifications-flyout/src/Notification.js, packages/notifications-flyout/src/behaviors/NotificationBehavior.test.js, packages/notifications-flyout/src/behaviors/NotificationFlyoutBehavior.js, packages/notifications-flyout/src/behaviors/NotificationFlyoutBehavior.test.js, packages/notifications-flyout/src/behaviors/PanelBehavior.test.js, packages/progress-ring/src/__gemini__/ProgressRing.stories-test.js, packages/progress-ring/src/presenters/mediumSVG.js, packages/radio-button/src/__gemini__/RadioButtonPresenter.stories-test.js, packages/storybook/package.json, packages/table/package.json, packages/theme-data/src/__stories__/components/ColorExample.js, packages/theme-data/src/__stories__/components/Example.js, packages/theme-data/src/utils/validateTheme.js, packages/top-nav/src/ProfileAction.js, packages/typography/src/__stories__/Typography.stories.js
> This is a feature branch PR working towards the removal of legacy packages. It is expected that this branch will fail CI.
Corrects lint rules broken due to the removal of legacy packages. Most of these errors should have been caught before, but for some reason are only failing now. 
Contributes to #1208
=> Fix: correct lint errors

packages/progress-ring/src/ProgressRing.js
Resolves: https://github.com/Autodesk/hig/issues/1260
=> fix: console error on progress ring default props

packages/icon-button/src/IconButton.js
Resolves: https://github.com/Autodesk/hig/issues/1275
=> fix: add icon css to icon-button

.gitignore, packages/theme-data/package.json, packages/theme-data/scripts/buildThemeArtifacts.js, yarn.lock
Extends the build scripts to generate artifacts (SCSS variables) for each theme via Style Dictionary.
Resolves #1211
=> Feat: SCSS theme data artifacts

.circleci/config.yml, package.json, scripts/post-release.sh, scripts/upgrade-dependents.sh
=> chore(release):  ensure dependents use latest version of `@hig/theme-data`

packages/spacer/package.json
Resolves: https://github.com/Autodesk/hig/issues/1288
=> chore: update spacer to a stable version

packages/theme-data/src/baseTheme/components/typography.js
=> feat: Add theme data for typography

packages/theme-data/src/utils/resolveTheme.js, packages/theme-data/src/utils/resolveTheme.test.js
Resolves: #1319 
Requested by @beauroberts
=> bug: resolve intermediate transforms when resolving

packages/button/src/presenters/ButtonPresenter.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/presenters/__snapshots__/FlyoutPresenter.test.js.snap, packages/spacer/package.json, packages/tooltip/src/__snapshots__/Tooltip.test.js.snap
Resolves: https://github.com/Autodesk/hig/issues/1332
=> fix: point button back to themes

packages/theme-context/README.md
=> fix: Update theme-context usage README

packages/side-nav/src/Submodule/submodule.scss
- make the js and css active states consistent
=> fix(side-nav): Update dark blue theme active link colors

packages/project-account-switcher/src/ProjectAccountSwitcher.js
Resolves https://github.com/Autodesk/hig/issues/1291
=> fix(project-account-switcher): close on project or account selection

packages/theme-data/src/__stories__/stories.js, packages/theme-data/src/baseTheme/components/formField.js, packages/theme-data/src/baseTheme/components/icon.js, packages/theme-data/src/baseTheme/unresolvedRoles.js
=> Update Storybook published theme data

packages/project-account-switcher/src/ProjectAccountSwitcher.js, packages/project-account-switcher/src/ProjectAccountSwitcher.test.js, packages/project-account-switcher/src/__snapshots__/ProjectAccountSwitcher.test.js.snap, packages/project-account-switcher/src/__stories__/getKnobs.js, packages/project-account-switcher/src/__stories__/stories.js, packages/project-account-switcher/src/behavior/ProjectAccountSwitcherBehavior.js, packages/project-account-switcher/src/presenters/ContentPresenter.js, packages/project-account-switcher/src/presenters/ContentPresenter.test.js, packages/project-account-switcher/src/presenters/ProjectAccountSwitcherPresenter.js, packages/project-account-switcher/src/presenters/ProjectAccountSwitcherPresenter.test.js
Resolves: https://github.com/Autodesk/hig/issues/1290
=> fix(project-account-switcher): add back controlled behavior

packages/icons/src/__stories__/renderStory.js
This includes the size in the name to make it more obvious how icons are used.
=> doc: update script to generate icon names in storybook

packages/label/src/Label.js, packages/label/src/Label.test.js, packages/label/src/__snapshots__/Label.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1383.
=> feat: allow label to accept arbitrary props

packages/behaviors/src/ControlBehavior.js, packages/behaviors/src/PressedBehavior.js, packages/behaviors/src/PressedBehavior.test.js
Resolves https://github.com/Autodesk/hig/issues/1457
=> fix: isPressed state should be off on blur

packages/icons/scripts/build-icons/writeBundle.js, packages/icons/src/__snapshots__/index.test.js.snap, packages/icons/src/icon.stylesheet.js, packages/icons/src/index.js, packages/icons/src/index.test.js
=> Feat: support color attribute on icons

packages/project-account-switcher/src/behavior/ProjectAccountSwitcherBehavior.js
Resolves https://github.com/Autodesk/hig/issues/1514.
=> fix: use proper state name for pas

packages/flyout/src/Flyout.js
Resolves: https://github.com/Autodesk/hig/issues/1518
=> fix: flyout throwing console errors

packages/theme-data/scripts/buildThemes.js
resolves #1393
For each theme
* resolvedRoles, unresolvedRoles, and metadata theme data available from
build/esm/unresolved folder as ES module
* resolvedRoles and metadata theme data availble as ES module from
build/esm
Typical use
```
import lightGrayTheme from '@hig/theme-data/build/esm/lightGrayHighDensityTheme';
```
When customizing a theme
```
import { unresolvedRoles as lightGrayTheme } from '@hig/theme-data/build/esm/unresolved/lightGrayMediumDensityTheme';
import { extendTheme, resolveTheme } from '@hig/theme-data';
const myUnresolvedRedTheme = extendTheme(lightGrayTheme, {
"colorScheme.accentColor": { value: "#ff0000" }
});
const myRedTheme = resolveTheme(myUnresolvedRedTheme);
```
=> Make theme data available as ES6 modules

packages/multi-downshift/package.json
Resolves: https://github.com/Autodesk/hig/issues/1509.
=> chore: change downshift to peer dependency

packages/icons/package.json, packages/icons/src/__stories__/Icons.stories.js, packages/icons/src/__stories__/renderStory.js
Also updates the typography dependency to use theme data.
Fixes #1479
=> chore: update storybook for icons to include color

packages/theme-data/src/colorSchemes/webLight/components/_oldColors.js, packages/theme-data/src/colorSchemes/webLight/components/button.js, packages/theme-data/src/colorSchemes/webLight/components/checkbox.js, packages/theme-data/src/colorSchemes/webLight/components/flyout.js, packages/theme-data/src/colorSchemes/webLight/components/input.js, packages/theme-data/src/colorSchemes/webLight/components/progressBar.js, packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
resolves https://github.com/Autodesk/hig/issues/1483
acceptance steps:
1) build theme-data on development and copy the contents of `build/json/webLightHighDensityTheme` and `build/json/webLightMediumDensityTheme` into another directory
1) repeat step 1 but on this branch
1) compare the contents of `resolvedRoles.json` from the directories that you copied from development and this branch (`vimdiff` is a helpful tool for this)
=> chore: better organize WebLight theme data

packages/theme-data/src/baseTheme/components/slider.js, packages/theme-data/src/baseTheme/unresolvedRoles.js, packages/theme-data/src/basics/colors.js, packages/theme-data/src/colorSchemes/darkBlue/components/slider.js, packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js, packages/theme-data/src/colorSchemes/lightGray/unresolvedRoles.js
As a developer
I can have theme data describing the Slider
so I can create a slider that matches the rest of my application
=> Add Slider theme data

packages/theme-data/src/baseTheme/components/tooltip.js, packages/theme-data/src/baseTheme/unresolvedRoles.js, packages/theme-data/src/colorSchemes/darkBlue/components/tooltip.js, packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js, packages/theme-data/src/colorSchemes/darkGray/components/tooltip.js, packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js, packages/theme-data/src/colorSchemes/webLight/components/_oldColors.js, packages/theme-data/src/colorSchemes/webLight/components/tooltip.js, packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
As a developer
I can have theme data describing the tooltip
so I can build a tooltip matching the HIG design language
=> Add Tooltip theme data

packages/theme-data/src/colorSchemes/darkBlue/components/button.js
Resolves https://github.com/Autodesk/hig/issues/1551.
=> fix: button theme data design updates

packages/dropdown/package.json, packages/multi-downshift/package.json, yarn.lock
Same as this PR but a newer version has since come out: https://github.com/Autodesk/hig/pull/1575.
=> Greenkeeper/default/downshift 3.2.0

packages/theme-data/src/utils/extendTheme.js, packages/theme-data/src/utils/mapValues.js
Resolves #1591 
It would be great if we could fast track this one for review and release! I don't want to short-circuit your process at all, we just have some consumers who are feeling the pain. Thank you!
=> perf: improve performance of `mapValues`, `extendTheme`

packages/icons/package.json, packages/icons/src/__stories__/Icons.stories.js
Resolves https://github.com/Autodesk/hig/issues/1594.
=> docs: update typography devdep for icons storybook

packages/theme-context/src/ThemeContext/ThemeContext.test.js, packages/theme-context/src/ThemeContext/createThemeProxy.js, packages/theme-context/src/ThemeContext/createThemeProxy.test.js, packages/theme-data/src/utils/generateAllThemes.js, packages/theme-data/src/utils/generateAllThemes.test.js
Related to https://github.com/Autodesk/hig/issues/1558
=> Deprecated roles console warn

packages/theme-data/src/baseTheme/components/divider.js, packages/theme-data/src/baseTheme/unresolvedRoles.js, packages/theme-data/src/colorSchemes/darkGray/components/divider.js, packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js
=> feat(theme-data): add divider

acceptance/package.json, acceptance/src/components/ThemeRepeater.js, acceptance/yarn.lock
Add Surface to acceptance app as dependency and also update horizontalPadding and verticalPadding prop values to reflect single letter convention for t-shirt sizes.
=> Add Surface to acceptance app as dependency

packages/skeleton-item/package.json, packages/skeleton-item/src/SkeletonItem.js, packages/skeleton-item/src/__snapshots__/SkeletonItem.test.js.snap
BREAKING CHANGE:
* Remove CSS classname
=> fix: release skeleton-item

packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/rich-text/src/__snapshots__/RichText.test.js.snap, packages/theme-data/src/baseTheme/components/textLink.js, packages/theme-data/src/colorSchemes/darkBlue/components/textLink.js
Resolves: https://github.com/Autodesk/hig/issues/1720.
=> fix: text-link theme-data design updates

acceptance/package.json, acceptance/src/pages/TabsPage.js, acceptance/yarn.lock
Resolves https://github.com/Autodesk/hig/issues/1715.
=> docs: update tabs in acceptance app

packages/icon-button/src/__snapshots__/IconButton.test.js.snap, packages/icon-button/src/presenters/IconButtonPresenter.js, packages/icon-button/src/presenters/__snapshots__/IconButtonPresenter.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1824.
=> fix: console errors for invalid props

packages/modal/README.md
Resolves https://github.com/Autodesk/hig/issues/1837.
=> docs: remove css import

packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/rich-text/src/__snapshots__/RichText.test.js.snap, packages/theme-data/src/baseTheme/components/textLink.js, packages/theme-data/src/colorSchemes/darkBlue/components/textLink.js
Also for https://github.com/Autodesk/hig/issues/1853.
=> feat: new text-link focus halo color

DEVELOPING.md
Update lerna url as reported by https://github.com/Autodesk/hig/issues/1868
=> docs: update lerna url in developing documents

packages/typography/src/Typography.js, packages/typography/src/Typography.test.js, packages/typography/src/__snapshots__/Typography.test.js.snap, packages/typography/src/__stories__/Typography.stories.js, packages/typography/src/__stories__/getKnobs.js, packages/typography/src/__stories__/infoOptions.js, packages/typography/src/__stories__/renderStory.js, packages/typography/src/__stories__/stories.js
Fix https://github.com/Autodesk/hig/issues/1704
=> Fix: props passing issue in typography

packages/side-nav/src/__stories__/ExampleSideNav.js, packages/side-nav/src/presenters/SideNav.js, packages/side-nav/src/presenters/SideNav.test.js, packages/side-nav/src/presenters/__snapshots__/SideNav.test.js.snap
feat [#1857](https://github.com/Autodesk/hig/issues/1857)
=> feat: Enable onClick events for sideNav headerLink and superHeaderLink

packages/button/src/Button.test.js, packages/button/src/__snapshots__/Button.test.js.snap, packages/button/src/presenters/ButtonPresenter.js
Fix https://github.com/Autodesk/hig/issues/1885
=> fix: allow passing classname to button

CONTRIBUTING.md, docs/sample-component/README.md, docs/sample-component/package.json, docs/sample-component/src/SampleComponentBreadcrumbs.js, docs/sample-component/src/SampleComponentBreadcrumbs.test.js, docs/sample-component/src/__gemini__/SampleComponentBreadcrumbs.gemini.js, docs/sample-component/src/__gemini__/SampleComponentBreadcrumbs.stories-test.js, docs/sample-component/src/__snapshots__/SampleComponentBreadcrumbs.test.js.snap, docs/sample-component/src/__stories__/SampleComponentBreadcrumbs.stories.js, docs/sample-component/src/__stories__/getKnobs.js, docs/sample-component/src/__stories__/infoOptions.js, docs/sample-component/src/__stories__/renderStory.js, docs/sample-component/src/__stories__/withThemeProvider.js, docs/sample-component/src/index.js, docs/sample-component/src/stylesheet.js
As request by @scmm17 , add a complete sample for contributing a HIG component, to be used as the `contribution example` in [CONTRIBUTION.md](https://github.com/Autodesk/hig/blob/development/CONTRIBUTING.md)
=> docs: add a complete sample component

packages/button/src/Button.js, packages/button/src/presenters/ButtonPresenter.js
Resolves https://github.com/Autodesk/hig/issues/1886
=> feat: enable stylesheet function prop on Button

packages/theme-data/README.md
Resolves https://github.com/Autodesk/hig/issues/1893.
=> docs: add LESS theme-data to readme

packages/input/src/Input.js, packages/input/src/Input.test.js, packages/input/src/presenters/InputHaloPresenter.js, packages/input/src/presenters/InputPresenter.js
resolves https://github.com/Autodesk/hig/issues/1895
=> fix: allow classname to be passed down in input

packages/text-area/src/TextArea.js, packages/text-area/src/TextArea.test.js, packages/text-area/src/__snapshots__/TextArea.test.js.snap
resolve https://github.com/Autodesk/hig/issues/1897
=> fix: allow className to be passed down in TextArea

packages/progress-ring/src/ProgressRing.js, packages/progress-ring/src/__stories__/ProgressRing.stories.js, packages/progress-ring/src/__stories__/getKnobs.js, packages/progress-ring/src/__stories__/renderStory.js, packages/progress-ring/src/__stories__/stories.js, packages/progress-ring/src/availableSizes.js, packages/progress-ring/src/constants.js, packages/progress-ring/src/presenters/ProgressRingPresenter.js, packages/progress-ring/src/presenters/ProgressRingPresenter.test.js, packages/progress-ring/src/presenters/__snapshots__/ProgressRingPresenter.test.js.snap, packages/progress-ring/src/presenters/stylesheet.js
Resolves: https://github.com/Autodesk/hig/issues/1912
=> feat: add props for customizing background color in ProgressRing

packages/flyout/package.json, packages/flyout/src/Flyout.js
Resolves https://github.com/Autodesk/hig/issues/1906
=> fix: children's onClick prop is discarded in Flyout

packages/text-area/src/TextArea.js, packages/text-area/src/TextArea.test.js, packages/text-area/src/__snapshots__/TextArea.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1898
=> feat: add stylesheet prop to TextArea

packages/dropdown/src/Dropdown.js, packages/dropdown/src/Dropdown.test.js, packages/dropdown/src/__snapshots__/Dropdown.test.js.snap, packages/dropdown/src/presenters/MenuPresenter.js, packages/dropdown/src/presenters/MenuPresenter.test.js, packages/dropdown/src/presenters/WrapperPresenter.js, packages/dropdown/src/presenters/__snapshots__/MenuPresenter.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1896
=> fix: allow classname to be passed down in dropdown

packages/banner/package.json, packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap, packages/banner/src/__snapshots__/Banner.test.js.snap, packages/banner/src/presenters/IconBackground/IconBackground.js
Resolves https://github.com/Autodesk/hig/issues/1933
=> fix: update Banner to the newest Icons version

packages/dropdown/package.json, packages/dropdown/src/__snapshots__/Dropdown.test.js.snap, packages/dropdown/src/presenters/InputPresenter.js, packages/dropdown/src/presenters/OptionPresenter.js, packages/dropdown/src/presenters/__snapshots__/OptionPresenter.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1936
=> fix: update Dropdown to the newest Icons version

packages/project-account-switcher/package.json, packages/project-account-switcher/src/presenters/ProjectAccountSwitcherPresenter.js
Resolves https://github.com/Autodesk/hig/issues/1941
=> fix: update ProjectAccountSwitcher to newest Icons version

packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap, packages/icon-button/src/IconButton.test.js, packages/icon-button/src/__snapshots__/IconButton.test.js.snap, packages/icon-button/src/presenters/IconButtonPresenter.js, packages/icon-button/src/presenters/IconButtonPresenter.test.js, packages/icon-button/src/presenters/__snapshots__/IconButtonPresenter.test.js.snap, packages/modal/src/__snapshots__/Modal.test.js.snap, packages/modal/src/presenters/__snapshots__/ModalHeaderPresenter.test.js.snap, packages/modal/src/presenters/__snapshots__/ModalPresenter.test.js.snap, packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/DismissButtonPresenter.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/IndicatorPresenter.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/top-nav/src/presenters/__snapshots__/HelpButtonPresenter.test.js.snap
Resolves https://github.com/Autodesk/hig/issues/1963
=> fix: prevent disabled IconButton from triggering onClick

CONTRIBUTING.md, DEVELOPING.md, WindowsSetup.md
Updated owners of the HIG components. Also gave more details on testing guidelines, and added a new section to the DEVELOPING guide on setting up a dev environment on Windows.
=> Docs: Update contribution guidelines

packages/theme-data/src/baseTheme/components/thumbnail.js, packages/theme-data/src/baseTheme/unresolvedRoles.js, packages/theme-data/src/colorSchemes/darkBlue/components/thumbnail.js, packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js, packages/theme-data/src/colorSchemes/darkGray/components/thumbnail.js, packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js
Resolves: https://github.com/Autodesk/hig/issues/1995
=> feat: add thumbnail theme-data

packages/theme-data/src/baseTheme/components/modal.js
Resolves https://github.com/Autodesk/hig/issues/2008.
=> fix: modal bg color should be surface level 100

packages/input/src/Input.js, packages/input/src/__stories__/getKnobs.js, packages/input/src/__stories__/stories.js, packages/input/src/presenters/InputHaloPresenter.js, packages/input/src/presenters/InputHaloPresenter.stylesheet.js, packages/input/src/presenters/InputHaloPresenter.test.js, packages/input/src/presenters/__snapshots__/InputHaloPresenter.test.js.snap, packages/theme-data/src/baseTheme/components/input.js
Implement error state as per https://github.com/Autodesk/hig/issues/2019
=> feat: add error state for Input

packages/banner/package.json, packages/components/package.json, packages/dropdown/package.json, packages/modal/package.json, packages/notifications-flyout/package.json, packages/notifications-toast/package.json, packages/side-nav/package.json, packages/text-area/package.json, packages/top-nav/package.json
- merge greenkeeper/default/@hig/input-1.2.0
- merge greenkeeper/default/@hig/icon-button-2.3.1
=> chore: greenkeeper update

packages/progress-bar/README.md, packages/progress-bar/src/ProgressBar.js, packages/progress-bar/src/ProgressBar.test.js, packages/progress-bar/src/__snapshots__/ProgressBar.test.js.snap, packages/progress-bar/src/stylesheet.js
resolves https://github.com/Autodesk/hig/issues/2036
=> Feat: add className and stylesheet props for progress bar

packages/timestamp/README.md, packages/timestamp/src/Timestamp.js, packages/timestamp/src/stylesheet.js
fix https://github.com/Autodesk/hig/issues/2043
=> feat: allow className and stylesheet props to be passed to Timestamp

packages/notifications-flyout/README.md
Resolves https://github.com/Autodesk/hig/issues/2165.
=> docs: remove css import from readme

packages/icon-button/src/IconButton.js
Resolves https://github.com/Autodesk/hig/issues/2166.
=> feat: title prop is no longer required

packages/modal/src/Modal.js, packages/modal/src/presenters/ModalHeaderPresenter.js, packages/modal/src/presenters/ModalPresenter.js
Resolves https://github.com/Autodesk/hig/issues/2179.
=> feat: allow PropTypes.node for title prop

packages/accordion/src/Accordion.js, packages/accordion/src/presenters/HeaderPresenter.js
Resolves https://github.com/Autodesk/hig/issues/2180.
=> feat: allow PropTypes.node for label prop

packages/theme-data/src/colorSchemes/darkBlue/components/button.js
Resolves https://github.com/Autodesk/hig/issues/2221.
=> fix: correct solid button background and border colors

packages/banner/src/BannerPresenter/BannerPresenter.js, packages/banner/src/BannerPresenter/presenters.js, packages/banner/src/__stories__/stories.js
Resolves https://github.com/Autodesk/hig/issues/2245.
=> fix: dismissButtonTitle prop was not working

packages/accordion/src/presenters/ContentPresenter.js
Resolves https://github.com/Autodesk/hig/issues/2237.
Was this https://github.com/Autodesk/hig/pull/2251 but there was a surge storybook issue.
=> fix: replace componentWillReceiveProps before React deprecates it

packages/icon-button/src/IconButton.js
Resolves https://github.com/Autodesk/hig/issues/2289.
=> fix: do not trigger focus/hover/pressed states when disabled

packages/theme-context/README.md
This is a fix commit to trigger the release, see previous chore commit for actual commit
=> fix: security update for dependency

packages/timestamp/src/Timestamp.js, packages/timestamp/src/Timestamp.test.js, packages/timestamp/src/__stories__/Timestamp.stories.js, packages/timestamp/src/constants.js, packages/timestamp/src/constants.test.js, packages/timestamp/src/index.js
Resolves https://github.com/Autodesk/hig/issues/2276.
=> feat: add timestampSequence prop to help with localization

packages/dropdown/package.json
Resolves https://github.com/Autodesk/hig/issues/2325.
=> fix: defaultValue when multiple is selected

packages/modal/src/Modal.js, packages/modal/src/__stories__/Modal.stories.js, packages/modal/src/presenters/ModalHeaderPresenter.js, packages/modal/src/presenters/ModalPresenter.js
Resolves https://github.com/Autodesk/hig/issues/2334.
=> fix: pass closeButtonAriaLabel to title attribute

packages/radio-button/README.md, packages/radio-button/src/presenters/ButtonPresenter.js, packages/radio-button/src/presenters/RadioButtonPresenter.js, packages/radio-button/src/presenters/RadioButtonPresenter.test.js, packages/radio-button/src/presenters/__snapshots__/RadioButtonPresenter.test.js.snap, packages/radio-button/src/presenters/stylesheet.js, packages/radio-button/src/presenters/stylesheet.test.js
Resolves: https://github.com/Autodesk/hig/issues/2201.
=> feat: add stylesheet and className props

packages/notifications-flyout/src/Notification.js, packages/notifications-flyout/src/NotificationsFlyout.js
Resolves https://github.com/Autodesk/hig/issues/2343.
=> fix: dismissButtonTitle prop was never exposed

packages/theme-data/src/baseTheme/components/menu.js, packages/theme-data/src/densities/highDensity/components/menu.js
menu.header.fontSize
menu.item.minHeight
=> fix: fix values for menu roles

packages/dropdown/src/Dropdown.js, packages/dropdown/src/__snapshots__/Dropdown.test.js.snap, packages/dropdown/src/presenters/InputPresenter.js, packages/dropdown/src/presenters/OptionPresenter.js, packages/dropdown/src/presenters/OptionPresenter.stylesheet.js, packages/dropdown/src/presenters/__snapshots__/InputPresenter.test.js.snap, packages/dropdown/src/presenters/__snapshots__/OptionPresenter.test.js.snap, packages/dropdown/src/presenters/constants.js
Resolves https://github.com/Autodesk/hig/issues/2273.
=> feat:  match the latest designs

README.md, packages/text-area/src/TextArea.js
Resolves https://github.com/Autodesk/hig/issues/2331
=> feat: allow ref forwarding to HTML textarea

packages/typography/src/Typography.js
Resolves https://github.com/Autodesk/hig/issues/2361.
=> feat: pass down a callback ref to root element

packages/checkbox/README.md, packages/checkbox/package.json, packages/checkbox/src/Checkbox.js, packages/checkbox/src/presenters/CheckPresenter.js, packages/checkbox/src/presenters/CheckboxPresenter.js, packages/checkbox/src/presenters/stylesheet.js, packages/checkbox/src/presenters/stylesheet.test.js
Resolves https://github.com/Autodesk/hig/issues/2198.
=> feat: add stylesheet and checkboxRef prop, pass down className

packages/progress-ring/package.json, packages/progress-ring/src/ProgressRing.js, packages/progress-ring/src/presenters/ProgressRingPresenter.js, packages/progress-ring/src/presenters/SVGPresenter.js, packages/progress-ring/src/presenters/stylesheet.js, packages/progress-ring/src/presenters/stylesheet.test.js
Resolves https://github.com/Autodesk/hig/issues/2188.
=> feat: add stylesheet prop, pass down className

packages/avatar/README.md, packages/avatar/src/Avatar.js, packages/avatar/src/Avatar.stylesheet.js, packages/avatar/src/Avatar.stylesheet.test.js
Resolves https://github.com/Autodesk/hig/issues/2186.
=> feat: add stylesheet prop

packages/flyout/src/presenters/PointerPresenter.js
Resolves https://github.com/Autodesk/hig/issues/2194.
=> fix: pass all props into stylesheet

packages/theme-data/src/baseTheme/components/avatarBundle.js, yarn.lock
=> theme-data/add-avatarBundle-data

packages/theme-data/src/baseTheme/components/avatarBundle.js
**This PR must be merged before Avatar Bundle PR https://github.com/Autodesk/hig/pull/2432**
Add new theme data for new  Avatar Bundle component as part of updates described in https://jira.autodesk.com/browse/ACWB-8852.
See Figma spec here:
https://www.figma.com/file/S657OgrT8eiU4TreWWYQi8/LIB_Components?node-id=528%3A15
Another commit with the Avatar Bundle component that uses this new data will follow this one.
=> feat(themeData): Add AvatarBundle spacings, colors etc (ACWB-8852)

packages/avatar-bundle/src/__snapshots__/AvatarBundle.test.js.snap
Fix failing snapshot tests in AvatarBundle component
=> refactor: fix snapshot tests

packages/profile-flyout/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap, packages/theme-data/src/baseTheme/components/avatar.js, packages/top-nav/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap
UX let me know that one Avatar background color was incorrect, fixing it in this PR.
=> fix(avatar): Correct one Avatar color

packages/menu/src/Menu.js, packages/menu/src/Menu.test.js, packages/menu/src/MenuGroup.js, packages/menu/src/MenuGroup.test.js, packages/menu/src/Option.js, packages/menu/src/__snapshots__/Menu.test.js.snap, packages/menu/src/__snapshots__/MenuGroup.test.js.snap, packages/menu/src/__snapshots__/Option.test.js.snap, packages/menu/src/__stories__/getKnobs.js, packages/menu/src/__stories__/stories.js, packages/menu/src/behaviors/MenuBehavior.js, packages/menu/src/presenters/MenuGroupPresenter.js, packages/menu/src/presenters/MenuPresenter.js, packages/menu/src/presenters/OptionPresenter.js, packages/menu/src/presenters/stylesheet.js
This PR is raised as a part of this discussion below.
https://autodesk.slack.com/archives/C5FLF7R46/p1625045686093600
=> perf(menu): added prop unselect, to remove the facility of uncheck in checkmark as per requirement

packages/notifications-flyout/src/Notification.js, packages/notifications-flyout/src/Notification.test.js, packages/notifications-flyout/src/NotificationsFlyout.js, packages/notifications-flyout/src/NotificationsFlyout.test.js, packages/notifications-flyout/src/__fixtures__/createSampleNotifications.js, packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/__stories__/Notification.stories.js, packages/notifications-flyout/src/behaviors/__snapshots__/NotificationFlyoutBehavior.test.js.snap, packages/notifications-flyout/src/presenters/NotificationPresenter.js, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap
allow custom notification click callback like marking the notification read on click
=> feat:(notifications-flyout): add onNotificationClick prop

packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/theme-data/src/baseTheme/system/colorScheme.js, packages/theme-data/src/colorSchemes/darkBlue/system/colorScheme.js
Redo of Bryan's PR with snap update
Original PR https://github.com/Autodesk/hig/pull/2485
=> fix: set success color for light gray to correct value

packages/tree-view/README.md, packages/tree-view/src/TreeView.js, packages/tree-view/src/behaviors/TreeViewBehavior.js
- change type for `label` prop from `string` to `node`
=> fix: tree-view label change prop type

packages/tree-view/src/presenters/fileview/TreeObjectSubTreeItem.js
switch subtree component label prop to accept node type
=> fix: label prop for subtree

README.md
=> Revert "fix: add readme commit to repo to try and fix bad release"

packages/side-nav/src/Search/Search.js, packages/side-nav/src/Search/Search.test.js
Issues demo in #2557 
demo of fix [here ](https://codesandbox.io/s/vigorous-chatterjee-8047m)
update state in SideNav.Search with props
=> fix: update state in SideNav.Search with props Issue#2557

packages/tree-view/src/TreeItem.js, packages/tree-view/src/presenters/SingleTreeNodeFolderPresenter.js, packages/tree-view/src/presenters/SingleTreeNodePresenter.js
- according to hig's coding convention, refactor and adjust the order of the properties.
=> refactor(TreeView): adjust the order of the properties

packages/table/src/TableDataCell.js
add props pass for multi select row
=> feat: add multi select functionality

packages/table/src/TableDataCell.js, packages/table/src/presenters/TableDataCellPresenter.js
=> refactor: add multiselect props

packages/tree-view/src/TreeItem.js, packages/tree-view/src/TreeView.js, packages/tree-view/src/behaviors/TreeViewBehavior.js, packages/tree-view/src/presenters/SingleTreeNodeFolderPresenter.js, packages/tree-view/src/presenters/SingleTreeNodePresenter.js, packages/tree-view/src/presenters/TreeItemPresenter.js, packages/tree-view/src/presenters/fileview/TreeObjectSubTreeItem.js
- allow label prop to accept a function as a param.
=> Tree view edit on select

packages/flyout/src/Flyout.js
This PR is raised as a part of this discussion below.
https://autodesk.slack.com/archives/C5FLF7R46/p1649220205511849
@wmui51 I have created this new PR for https://github.com/Autodesk/hig/pull/2683 as too many files were added after some issue with rebasing
=> fix: Updating the Flyout refs after rendering to show tooltip

packages/flyout/src/Flyout.js
=> Revert "fix: Updating the Flyout refs after rendering to show tooltip"

packages/flyout/src/Flyout.js
This PR is raised as a part of this discussion below.
https://autodesk.slack.com/archives/C5FLF7R46/p1649220205511849
Verified the storybook:
=> fix: Updating the Flyout refs in the callbacks sent as props to the child component

acceptance/src/fixtures/SortColumns.js, acceptance/src/pages/TablePage.js, packages/table/src/Table.js, packages/table/src/TableHeaderCell.js, packages/table/src/presenters/TableHeaderCellPresenter.js, packages/table/src/presenters/TablePresenter.js, packages/table/src/presenters/stylesheet.js
feat: add sorting capability to group logic
=> feat: add sort by group logic

acceptance/src/fixtures/SortColumns.js, packages/table/src/presenters/TableHeaderCellPresenter.js, packages/table/src/presenters/TablePresenter.js
fix: sort icon on hover for single and group headers
=> fix: sort icons

acceptance/src/fixtures/DataGroupComponent.js, acceptance/src/pages/TablePage.js, packages/table/src/Table.js, packages/table/src/components/DataGroupComponent.js, packages/table/src/presenters/RenderTable.js, packages/table/src/presenters/TablePresenter.js, packages/table/src/presenters/stylesheet.js
- add table group select all functionality
=> feat: add table group select all

acceptance/src/fixtures/TableObjectBasic.js, acceptance/src/fixtures/TableObjectCustom.js, packages/table/src/behaviors/TableBehavior.js, packages/table/src/presenters/RenderTable.js, packages/table/src/presenters/TablePresenter.js
feat: add ability to show/hide columns automatically by passing in hidden columns from object.
=> feat: auto show/hide columns

packages/stories/fixtures/TableGroup/DataGroupComponent.js
fix: edit group table storybook prop
=> fix: edit group table storybook prop
