Autodesk/hig

src/web/components/global-nav/container/sub-nav/tabs/tab/tab.js
Corrects a typo/bug. Setting label after initialization caused an error because `setAttr` is not a function.
=> Set tab label to title attribute

DEVELOPING.md, package.json
Use `concurrently` package to startup the http server, run gemini tests, and shut them both down when tests have finished.
=> Run http server and gemini in a single command

.gitignore, index.html
CircleCI generates a nohup.out file which is causing the diff check portion of the deploy script to fail, and thence failing CI.  
add nohup.out to .gitignore.
Also, index.html appears to be out of date.
=> regenerate files and gitignore nohup.out

deploy/compile-gh-pages.js, index.html
In  my enthusiasm for viewing the index.html file locally with http-server, I forgot that github pages requires you to prefix the URL to source files with the project name.
Also, gemini files should be excluded from the test file glob pattern. 
Although viewing the static files works fine locally, because of the prefix to the path on index.html, This breaks the links locally with http-server.  But it should work on github  #pages.
It also matches only on files w/ path matching `/src/**/tests/test*.html` .
=> exclude gemini, prefix href with /hig

src/web/components/global-nav/top-nav/top-nav.js
Since we can't use names of  classes to determine the comment, just do it the old way.  Also, accept/respect use of reference instance to control order of shortcuts/help.
=> put back old code, use reference instance

src/interface/interface.json, src/web/components/global-nav/top-nav/profile/_profile-flyout-content/profile-flyout-content.js, src/web/components/global-nav/top-nav/profile/profile.js
To enable setting the sign out link in initialOptions,
* Add signOutLink to defaults list for Profile
* Add signOutLink to props list when creating signOutButton
* Set a default value of '#' for the signOutLink (for completeness; it's not actually necessary)
=> Enable more settings in Profile for Orion Profile component

src/web/basics/form-elements/text-field/text-field.js
The `enable` method was disabling the text field 😂.
Fixes that.
=> Correctly reenable TextField when disabled

src/web/basics/button/button.html, src/web/basics/icon-button/icon-button.html
Button and IconButton templates include `tabindex` attribute so they render the same initially as they will when disabled and reenabled.
=> Render buttons with tabindex

src/web/components/global-nav/sub-nav/tabs/tab/tab.html
Active is not a default specified in interface.json.
=> Remove unsupported props from Tab template

src/implementations/react/src/adapters/FormElements/CheckboxAdapter.js, src/implementations/react/src/adapters/FormElements/__snapshots__/CheckboxAdapter.test.js.snap, src/implementations/react/src/adapters/FormElements/__snapshots__/RadioButtonAdapter.test.js.snap, src/implementations/react/src/elements/basics/form-elements/TextField.js, src/implementations/react/src/elements/components/FormElements/Checkbox.js, src/implementations/react/src/elements/components/FormElements/Checkbox.story.js, src/implementations/react/src/elements/components/Modal.js, src/implementations/react/src/playground/sections/CheckboxSection.js, src/implementations/react/src/react-hig.js, src/implementations/react/src/stories/index.js, src/implementations/vanilla/src/basics/form-elements/input-button/input-button.js
This is a fix for #199, "Radiobutton "checked" state does not actually have "checked" attribute in HTML"
It fixes it for both Checkbox and Radiobutton. This also includes a Checkbox component (but not a RadioButton component).   The Checkbox component lets the consumer set the initial "checked" state but right now there is no way for the consumer to change it afterward;  the user will still have to click on the checkbox to change the state. I don't know of a way to allow both things (@nfiniteset ?)
The RadioButton component will be in a different PR.
=> Checkbox HIG component toggles checked attribute, plus Checkbox component

src/implementations/react/src/adapters/ModalAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.story.js, src/implementations/react/src/elements/components/Modal.js, src/implementations/react/src/elements/components/Modal.story.js, src/implementations/react/src/playground/sections/ModalSection.js
#252 This lets you put HTML/React component content inside of Modal:
```
const buttonProps = [
{ title: 'Cancel', type: 'secondary', onClick: this.closeModal },
{ title: 'Ok', onClick: this.closeModal }
];
...
return (
<PlaygroundSection title="Modal">
<Button title="Open modal" onClick={this.openModal} />
<Modal
title="Are you sure?"
isOpen={this.state.isOpen}
buttons={buttonProps}
body="This is the text body of my modal"
headerColor="gray"
onClose={this.closeModal}
>
<h1><u>This is my HTML title</u></h1>
<p><i>This is my HTML content.</i></p>
</Modal>
</PlaygroundSection>
);
```
=> Allow any HTML/components side of Modal

src/implementations/vanilla/src/components/table/tests/tests-table.html
Story: https://github.com/Autodesk/hig/issues/237
Replaces backticks with quotes in order to maintain ES5 compatibility in the static table test.  This allows the page to build in IE11
http://calm-cream.surge.sh/src/components/table/tests/tests-table.html
=> Resolve ES5 compatibility bug in static table test

src/implementations/react/package-lock.json, src/implementations/react/package.json, src/implementations/react/src/adapters/GlobalNav/GlobalNavAdapter.js, src/implementations/react/src/adapters/GlobalNav/SideNav/SideNavAdapter.js, src/implementations/react/src/adapters/GlobalNav/SideNav/SideNavAdapter.test.js, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/GroupAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/LinkAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/ModuleCollapseAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/SearchAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/SideNavAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/SideNav/__snapshots__/SubmoduleAdapter.test.js.snap, src/implementations/react/src/adapters/GlobalNav/__snapshots__/GlobalNavAdapter.test.js.snap, src/implementations/react/src/adapters/SlotAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.js, src/implementations/react/src/adapters/SpacerAdapter.test.js, src/implementations/react/src/elements/components/GlobalNav/GlobalNav.js, src/implementations/react/src/elements/components/GlobalNav/SideNav/SideNav.js, src/implementations/react/src/elements/components/GlobalNav/Slot.js, src/implementations/react/src/elements/components/GlobalNav/index.js, src/implementations/react/src/hig-react.js, src/implementations/react/src/playground/index.js, src/implementations/vanilla/src/components/global-nav/side-nav/side-nav.html, src/implementations/vanilla/src/components/global-nav/side-nav/side-nav.js, src/implementations/vanilla/src/components/global-nav/side-nav/side-nav.scss, src/implementations/vanilla/src/index.js, src/interface/interface.json
Adds a slot to SideNav.
When using the prop-controlled GlobalNav, provide rendered react markup to `props.sideNav.slot`.
```js
const props = {
sideNav: {
slot: (
<Button title="Designer Toolkit" type="secondary" />
<Button title="Git Repository" />
)
}
}
return (<GlobalNav {...props} />);
```
=> Add slot to side nav

.circleci/config.yml
Extract test run into build and test steps with dependency between them.  
This will later allow having a separate task to validate that the hig-react npm module version has been incremented.  It will also allow having concurrent vanilla and react test bulds and runs
=> Use CircleCI V2 Workflows

.circleci/config.yml
Adds deploy job to CircleCI tasks
This job will be run only on master
It's also configured to only run when a version tag in the format `v0.18.0` is present. This will need to be confirmed in master
=> Add hig-react deploy task to CircleCI

.circleci/config.yml
Includes: https://github.com/Autodesk/hig/pull/332
This will require changing the Github/CircleCI integration accordingly for these checks:
* vanilla-setup
* react-setup
* vanilla-build
* react-build
* **vanilla-test (required)**
* **react-test (required)**
* react-validation (eventually required, see below)
* react-deploy
The *build* checks don't need to be required explicitly, they're required implicitly as a dependency of the other checks
The *react-validation* check can be required once the versioning/deployment workflow has been established
=> Concurrent CircleCI jobs

src/implementations/react/package.json
The stage (prepublish) where [these failures are happening on CircleCI](https://circleci.com/gh/Autodesk/hig/1792) is unnecessary and actually [deprecated by npm](https://docs.npmjs.com/misc/scripts#deprecation-note)
Not sure if this will resolve the failures but it's a start
=> Remove deprecated prepublish script

packages/vanilla/package.json, packages/vanilla/src/basics/flyout/tests/test-flyout_ja.html, packages/vanilla/src/helpers/js/i18n.js, packages/vanilla/src/index.js, packages/vanilla/src/languages/en/hig-vanilla-tests.json, packages/vanilla/src/languages/ja/hig-vanilla-tests.json
**Change:**
1. Add i18next module
2. Extract strings from test html to resource file (English/Japanese)
3. Add a localized test html
**Discussion:**
As we discussed with @recyclerobot the other day, we would like to add localized strings in test pages to make sure HIG elements work with in different languages/locales.
The purpose of this PR is to discuss and find an agreement how to implement **test** pages. We paid attention to some aspects:
- Easy to implement based on the existing test pages
- To follow i18n best practices as much as possible so that these examples could be used as a base for real implementation
- To avoid mixed-language page because this is not real case in general and we may want to apply different CSS (especially font related settings) to verify the rendering result …
=> [Discussion] Example to add localized strings to test page

packages/vanilla/src/components/button/button.html, packages/vanilla/src/components/button/button.js, packages/vanilla/src/components/global-nav/side-nav/group/module/module.html, packages/vanilla/src/components/global-nav/side-nav/group/module/module.js, packages/vanilla/src/components/global-nav/side-nav/group/module/submodule/submodule.html, packages/vanilla/src/components/global-nav/side-nav/group/module/submodule/submodule.js, packages/vanilla/src/components/global-nav/side-nav/link/link.html, packages/vanilla/src/components/global-nav/side-nav/link/link.js, packages/vanilla/src/components/global-nav/top-nav/help/option/option.js, packages/vanilla/src/components/global-nav/top-nav/shortcut/shortcut.html, packages/vanilla/src/components/global-nav/top-nav/shortcut/shortcut.js, packages/vanilla/src/components/icon-button/icon-button.js
I went through every component with a `setLink` method and treated them all the same way.
- `setLink` adds and removes the `href` attribute as needed.
- template includes/excludes `href` attribute based on value of `link`.
Completes #636
=> Linkable things without links dont have href attr

packages/react/src/elements/components/GlobalNav/SideNav/SideNav.test.js, packages/react/src/elements/components/GlobalNav/SideNav/WithState.js, packages/react/src/elements/components/GlobalNav/SideNav/model.js, packages/react/src/elements/components/GlobalNav/SideNav/model.test.js
This change no longer activates the first submodule.
=> [SideNav] Clicking a module only toggles expand/collapse

packages/interface/interface.json, packages/react/src/adapters/GlobalNav/SideNav/ModuleAdapter.js, packages/react/src/adapters/GlobalNav/SideNav/ModuleAdapter.test.js, packages/react/src/elements/components/GlobalNav/SideNav/SideNav.test.js, packages/react/src/elements/components/GlobalNav/SideNav/model.js, packages/react/src/elements/components/GlobalNav/SideNav/model.test.js, packages/react/src/elements/components/GlobalNav/TopNav/Help/Option.test.js, packages/react/src/playground/index.js, packages/vanilla/src/components/global-nav/side-nav/group/module/module.js, packages/vanilla/src/components/global-nav/side-nav/group/module/module.scss
In https://github.com/Autodesk/hig/pull/659, I omitted the part where the icon and vertical line still indicate a module is semi-active.
This PR also updates the playground to not do anything additional to the sidenav on navigation (fixes https://github.com/Autodesk/hig/issues/648).
=> [SideNav] onNavigation changes and "active" modules

packages/react/src/elements/components/Typography.js, packages/react/src/elements/components/Typography/Body.js, packages/react/src/elements/components/Typography/Bold.js, packages/react/src/elements/components/Typography/Caption.js, packages/react/src/elements/components/Typography/Disabled.js, packages/react/src/elements/components/Typography/H1.js, packages/react/src/elements/components/Typography/H2.js, packages/react/src/elements/components/Typography/H3.js, packages/react/src/elements/components/Typography/Sub1.js, packages/react/src/elements/components/Typography/Sub2.js, packages/react/src/elements/components/Typography/Text.js
At the expense of some repetition, this makes it much easier for our docgen plugin to annotate
individual typography components. It also more accurately documents the `children` prop instead of `text`, since the interfaces for Typography and TypographyAdapter differ slightly.
=> Bugfixes: Autogenerate Typography component docgenInfo

packages/react/src/elements/components/GlobalNav/TopNav/Search.js, packages/react/src/elements/components/Typography/Body.js, packages/react/src/elements/components/Typography/Bold.js, packages/react/src/elements/components/Typography/Caption.js, packages/react/src/elements/components/Typography/Disabled.js, packages/react/src/elements/components/Typography/H1.js, packages/react/src/elements/components/Typography/H2.js, packages/react/src/elements/components/Typography/H3.js, packages/react/src/elements/components/Typography/Sub1.js, packages/react/src/elements/components/Typography/Sub2.js, packages/react/src/elements/components/Typography/Text.js
1. Ensure search option is focused on mouseover.
2. Cleans up an extra proptype from https://github.com/Autodesk/hig/pull/669.
=> Bugfixes: Search - Set focus on mouseover

packages/react/src/elements/components/GlobalNav/readme.md
Spotted the `README.md` had the wrong term used for showing the side by by default, fixed
=> sideNavOpenByDefault doco fix

packages/vanilla/src/basics/form-elements/input-button/input-button.scss
Here's the playground with a dark-themed background:
=> Transparent backgrounds on radio buttons and checkboxes

packages/react/src/elements/components/Flyout.js, packages/react/src/elements/components/Flyout.test.js
Changes to the website necessitated being aware of whether the flyout was open or closed, and to initially render it open. This interface seemed to be the best way to achieve that without totally removing open/close state from the component.
=> Features: Prop-driven Flyout

packages/react/src/elements/components/Table/SelectableTable.js, packages/react/src/playground/sections/SelectableTableSection.js
While investigating https://github.com/Autodesk/hig/issues/627 I found some unexpected behavior that prevented the `selected` attributes from propagating as `data` props.
=> Bugfixes: Selecting all in selectable table

packages/react/src/adapters/FormElements/TextFieldAdapter.js, packages/react/src/adapters/FormElements/TextFieldAdapter.test.js, packages/react/src/playground/sections/TextFieldSection.js
Adds text field error examples to playground
=> Allow empty errors to trigger TextField error state

packages/react/.storybook/addons.js, packages/react/.storybook/arrayToObject.js, packages/react/.storybook/config.js, packages/react/package.json, packages/react/stories/Button.js, packages/react/stories/Typography.js, packages/react/yarn.lock, packages/vanilla/src/components/button/button.js, packages/vanilla/src/components/global-nav/side-nav/group/module/module.js, packages/vanilla/src/components/global-nav/side-nav/group/module/submodule/submodule.js, packages/vanilla/src/components/global-nav/side-nav/link/link.js, packages/vanilla/src/components/global-nav/top-nav/help/option/option.js, packages/vanilla/src/components/global-nav/top-nav/shortcut/shortcut.js, packages/vanilla/src/components/icon-button/icon-button.js
Include storybook addons:
* Knobs, for allowing viewer to edit props
* Notes, for additional documentation
* Viewport, for toggling device sizes
This also led me to discover some typos in HIG vanilla whose code paths weren't being triggered by our tests.
=> Chores: Add storybook addons

packages/vanilla/src/components/progress-ring/progress-ring-determinate.js, packages/vanilla/src/components/progress-ring/progress-ring-indeterminate.js
Before, when using a progress ring inside of my 3ds Max plugin using a Qt Web app, I would get `bundle.js:13722Uncaught TypeError: this.segments.forEach is not a function`.
This is because this.segments actually ended up being only an object (`typeof this,segments === object`). So casting it in Array with `Array.from()` from the instantiation fixes the problem.
You can see below the before and after (Left ring = Determinate ring; Ring ring = Indeterminate ring). (And yes, in the first pic, there is supposed to be two rings, but one of them just doesn't appear)
=> Fix Progress ring inside Qt web page

packages/react/.eslintrc.js, packages/react/src/adapters/HIGAdapter/MapsEventListener.js, packages/react/src/adapters/HIGAdapter/MountedByHIGParent.js, packages/react/src/adapters/HIGAdapter/MountedByHIGParentList.js, packages/react/src/adapters/HIGAdapter/MountsAnyChild.js, packages/react/src/elements/components/Avatar/index.js, packages/react/src/elements/components/Icon/Icon.js, packages/react/src/elements/components/IconButton/IconButton.js, packages/react/src/elements/components/Table/HeaderCheckbox.js, packages/react/src/elements/components/Table/RowCheckbox.js, packages/react/src/elements/components/Table/SelectableTable.js, packages/react/src/elements/components/Table/Table.js, packages/react/src/elements/components/Tabs/PlaceholderTab.js, packages/react/src/elements/components/Toast/Toast.test.js, packages/react/src/playground/index.js, packages/react/src/playground/sections/NotificationsSection.js, packages/react/src/playground/sections/PasswordFieldSection.js, packages/react/src/playground/sections/TextFieldSection.js, packages/react/src/playground/sections/TypographySection.js
This primarily comes from CircleCI trying to deploy the playground from `development`.
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.
Failed to compile.
./src/elements/components/Avatar/index.js
Line 40:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
```
As it turns out, it's easier (and better) to follow the disabled `jsx-a11y` and `react/prop-types` rules. We no longer need to keep them disabled.
=> Chores: Re-enable useful ESLint rules

packages/banner/src/Banner.js, packages/banner/src/Banner.test.js, packages/banner/src/BannerContainer.js, packages/banner/src/BannerContainer.test.js, packages/banner/src/BannerPresenter/BannerPresenter.js, packages/banner/src/BannerPresenter/BannerPresenter.test.js, packages/banner/src/BannerPresenter/banner-presenter.scss, packages/banner/src/BannerPresenter/presenters.js, packages/banner/src/__stories__/Banner.stories.js
This PR updates the `Banner` component's design in response to feedback. The API has also been updated to correlate with the design changes.
Resolves #830
> **Snapshot tests will fail in the future since jest isn't setup.**
I'd rather not spend time getting this setup since @eskfung is already working on it.
```js
function BannerWithAMessage() {
return <Banner>INFO: This is an informative message.</Banner>
}
```
```js
const renderBannerActions = ({ isWrappingActions }) => (
<Banner.Interactions isWrappingActions={isWrappingActions}>
<Banner.Action>
<Button title="Click Me" />
</Banner.Action>
</Banner.Interactions>
);
function BannerWithAnAction() {
return <Banner actions={renderBannerActions}>ISSUE: This is a warning message.</Banner>;
}
```
=> feat(banner): Tweak Banner design and API

.circleci/config.yml, packages/banner/.babelrc, packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap, packages/react/src/elements/components/Icon/__snapshots__/Icon.test.js.snap, packages/storybook/jest.config.js, packages/storybook/package.json, packages/storybook/support/jest/fileMock.js, packages/storybook/support/jest/matchers/toBeConstants.js, packages/storybook/support/jest/matchers/toHavePropTypesAndDocgenInfo.js, packages/storybook/support/jest/matchers/toImplementHIGInterfaceOf.js, packages/storybook/support/jest/setupTests.js, yarn.lock
* Configure Jest to run from one location. I threw it into the storybook package, but it should be pretty portable - maybe even to the repo root.
* Updated stale snapshots
* Use https://github.com/jest-community/jest-runner-eslint to handle linting and unit tests in one command.
* Investigate additional benefits from using `jest --projects`
* Clean up hig-react dependencies and remove unused code examples
* Update packages
=> Chores: Centralized Jest config

packages/banner/package.json, packages/icon-button/package.json, packages/icon/package.json, packages/icons/package.json, packages/skeleton-item/.babelrc, packages/skeleton-item/package.json, packages/skeleton-item/src/SkeletonItem.js, packages/skeleton-item/src/SkeletonItem.test.js, packages/skeleton-item/src/__snapshots__/SkeletonItem.test.js.snap, packages/skeleton-item/src/__stories__/SkeletonItem.stories.js, packages/skeleton-item/src/index.js, packages/skeleton-item/src/index.test.js, packages/skeleton-item/src/skeleton-item.scss, packages/themes/package.json, packages/themes/src/__stories__/ThemeContext.stories.js, packages/themes/src/index.js, packages/themes/src/index.test.js, packages/themes/src/themes/HIGDarkBlueTheme.js, packages/themes/src/themes/Themes.test.js, packages/themes/src/themes/index.js, packages/themes/src/themes/index.test.js, packages/typography/package.json
See https://github.com/Autodesk/hig/issues/674
=>  Features: Skeleton Item published independently

packages/top-nav/src/presenters/ProfileContent.js, packages/top-nav/src/top-nav.scss
Fixes incorrect styles in `TopNav` component. Sadly, one the fixes is a hack that will need to be resolved by migrating the `Flyout` component from Vanilla.
* [Release `@hig/top-nav@0.1.0-alpha.40ad6b99`](https://www.npmjs.com/package/@hig/top-nav)
* [Storybook](https://hig-fix-top-nav-styles.surge.sh/?knob-Name=Jon%20Snow&knob-Size=large&selectedKind=TopNav&selectedStory=accounts&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
=> fix(top-nav): Correct flyout styling

packages/top-nav/src/__stories__/TopNav.stories.js, packages/top-nav/src/top-nav.scss
Technically speaking, logos should be allowed to be any size within the TopNav.
We can provide additional components (e.g. `LogoImage`) to facilitate having components at the recommended size.
=> fix(top-nav): Remove unnecessarily restrictive logo styles

.circleci/config.yml
For a successful publish, Circle needs to cache and restore the `build/` directory
=> fix(rich-text): Have Circle publish @hig/rich-text/build

packages/top-nav/package.json, yarn.lock
* Updated the `@hig/avatar` dependency to the latest version to receive the fix for #889.
* Eventually this update process will be automated.
=> chore(top-nav): Update avatar dependency

packages/side-nav/src/containers/docked.scss, packages/side-nav/src/presenters/side-nav.scss
It was a little confusing that only the containers change based on the theme. Making some adjustments so that the docked container shadow still appears.
=> fix(side-nav): Apply themes directly to SideNav

.circleci/config.yml, packages/components/README.md, packages/components/integration/imports.test.js, packages/components/package.json, packages/components/scripts/build.js, packages/scripts/buildPackage.js, yarn.lock
This adds the `@hig/components` package as described in #768 
* No source files exist. The entire package is built from a script, which is configured by the `package.json`. 
* Some packages couldn't be added due to their dependency upon `hig-vanilla`. They can be added once their source is migrated.
* Since each dependency is versioned, we have control over exactly which versions of what components are exported.
* Duplicate styles are merged in the main stylesheet via [Clean CSS](https://www.npmjs.com/package/clean-css#minify-method).
```jsx
import * as HIG from "@hig/components";
import "@hig/components/build/index.css";
<HIG.Button title="Click Me" />;
```
```jsx
import { Button } from "@hig/components";
import "@hig/components/build/button.css";
<Button title="Click Me" />;
```
```jsx …
```
=> Add @hig/components package

packages/text-field/src/TextField.js, packages/text-field/src/TextFieldController.js, packages/text-field/src/TextFieldPresenter.js, packages/text-field/src/__stories__/getKnobs.js, packages/text-field/src/index.js, packages/text-field/src/index.test.js, packages/text-field/src/presenters/Input.js, packages/text-field/src/presenters/Input.test.js
The current, single export from `@hig/text-field` is a controlled component. The state of the input's value is encapsulated inside, and changing the value is handled through the change handler, instead of through updates to the value prop.
In refactoring Dropdown, I found I would want to use a `TextField` to implement a combobox-type input. In this component, the state of the input would need to be hoisted up to the Dropdown component, and passed _down_ to a child `TextField`. So, it makes sense for us to provide a component that is completely driven by props -- with state management left as an exercise for the consumer.
* Support a new `readOnly` prop.
* Split `TextField` into `TextFieldPresenter` and `TextFieldController`. Export `TextFieldPresenter`.
=> feat: Prop-driven TextField

packages/components/package.json, packages/components/scripts/build.js, packages/scripts/bin/build.js
Instead of importing modules to determine the named exports, the build script now uses Esprima to parse modules, and retrieves the named exports from the AST.
This makes the build system agnostic to the functionality within the modules, making it much more stable and flexible.
Build scripts now properly exit when errors occur.
The following components have been added to `@hig/components`:
* `@hig/notifications-flyout`
* `@hig/notifications-toast`
* ~`@hig/profile-flyout`~
* ~`@hig/project-account-switcher`~
=> Feature: Add components to @hig/components

packages/top-nav/src/top-nav.scss
This prevents the TopNav from shrinking when used as a flex element.
=> fix(style): Add `min-height` property

DEVELOPING.md
* Correct Node version range. The sub-dependency `upath@1.0.4` is incompatible with Node v10.
* Windows Subsystem for Linux has now been tested, and it works just fine.
=> Docs: Update prerequisites

packages/semantic-release-config/package.json, packages/semantic-release-config/src/createReleaseConfig.js, yarn.lock
> [Upgrade Dependents](https://github.com/morrisallison/upgrade-dependents) will discover and upgrade all compatible dependents within a directory.
This will add step 4 of `lerna publish` to our release strategy:
> Update all dependencies of the updated packages with the new versions, specified with a caret (^).
[lerna/lerna](https://github.com/lerna/lerna#publish)
=> Chore: Add release plugin to upgrade package dependents

packages/tabs/README.md, packages/tabs/package.json, packages/tabs/src/Tab.js, packages/tabs/src/Tabs.js, packages/tabs/src/Tabs.test.js, packages/tabs/src/__snapshots__/Tabs.test.js.snap, packages/tabs/src/__stories__/infoOptions.js, packages/tabs/src/__stories__/renderStory.js, packages/tabs/src/__stories__/stories.js, packages/tabs/src/alignments.js, packages/tabs/src/alignments.test.js, packages/tabs/src/index.js, packages/tabs/src/index.test.js, packages/tabs/src/presenters/TabPresenter.js, packages/tabs/src/presenters/TabPresenter.scss, packages/tabs/src/presenters/TabPresenter.test.js, packages/tabs/src/presenters/TabsPresenter.js, packages/tabs/src/presenters/TabsPresenter.scss, packages/tabs/src/presenters/TabsPresenter.test.js, packages/tabs/src/presenters/__snapshots__/TabPresenter.test.js.snap, packages/tabs/src/presenters/__snapshots__/TabsPresenter.test.js.snap, packages/tabs/src/tab.scss, packages/tabs/src/tabs.scss, yarn.lock
* Remove `hig-react` dependency
* Add support for custom tab styling via a render prop on the `Tab` component
* Improve markup to be more semantic
* Use `React.Fragment` for the outer container when supported
* Resolves #962
* [Storybook](http://hig-feat-tabs-962.surge.sh/?selectedKind=Tabs)
* [CodeSandbox](https://codesandbox.io/s/4xl2q3kkq4) - custom tab rendering
=> Feat: Re-implement Tabs

packages/utils/src/generateId.js, packages/utils/src/generateId.test.js, packages/utils/src/index.js, packages/utils/src/index.test.js
Having component presenters generate their own HTML ids has created difficulty in enzyme snapshot testing. The ID is random and is generated on each render
This branch extracts the logic that's used by the pure React checkbox component (https://github.com/Autodesk/hig/pull/1025) to generate its ID into a new `utils` module `utils/generateId`
This branch doesn't implement the function - will roll it out in the above Checkbox branch as well as Radio Button in https://github.com/Autodesk/hig/pull/1043
=> Util function to generate IDs for components

packages/checkbox/__mocks__/@hig/utils.js, packages/checkbox/src/CheckboxPresenter/CheckboxPresenter.js, packages/checkbox/src/CheckboxPresenter/CheckboxPresenter.test.js, packages/checkbox/src/CheckboxPresenter/__snapshots__/CheckboxPresenter.test.js.snap, packages/checkbox/src/__snapshots__/Checkbox.test.js.snap
Currently, there's no way to mock the checkbox HTML id when doing Enzyme snapshot testing.  
This branch updates to use the shared `@hig/utils/generateId` function to generate that ID. 
Additionally, it adds a Jest mock for that function in the `CheckboxPresenter` test
=> Use shared id generator to generate checkbox HTML id

packages/dropdown/src/__stories__/getKnobs.js, packages/slider/package.json, packages/slider/src/Slider.js, packages/slider/src/Slider.test.js, packages/slider/src/__stories__/getKnobs.js, packages/storybook/utils/controlledObject.js, packages/storybook/utils/controlledText.js, packages/storybook/utils/index.js
The Slider component was migrated from vanilla (was called Range before), but was never published. This corrects the controlled behavior and prepares `@hig/slider` for release.
=> Feat: cleanup slider for release

packages/dropdown/src/Dropdown.js
Story: https://github.com/Autodesk/hig/issues/1067
Downshift 2.0.20 altered the arguments for *getMenuProps* which we utilize in Dropdown.  The method now requires that a ref be passed in, or that the check be suppressed.  Since it appears that we're not currently utilizing refs in the Dropdown, we've opted for the latter
w/ @wmui51
=> Suppress ref check error to account for new validation in Downshift 2.0.20

packages/theme-data/src/utils/resolveTheme.js, packages/theme-data/src/utils/resolveTheme.test.js
=> fix(theme-data): allow `transform` to be overridden by referencer

packages/input/src/Input.js, packages/input/src/presenters/InputPresenter.js, packages/input/src/presenters/InputPresenter.test.js, packages/input/src/presenters/__snapshots__/InputPresenter.test.js.snap
Issue: https://github.com/Autodesk/hig/issues/1078
As described in https://github.com/Autodesk/hig/issues/1078, we'd like to link form element components with Label components.  The Input element doesn't support passing in an ID for its HTML id.  
This branch adds the `id` prop to Input and updates tests accordingly
=> Pass optional HTML id prop to Input

packages/dropdown/src/Dropdown.js, packages/dropdown/src/Dropdown.test.js, packages/dropdown/src/__snapshots__/Dropdown.test.js.snap, packages/dropdown/src/__stories__/getKnobs.js, packages/dropdown/src/__stories__/stories.js, packages/dropdown/src/behaviors/TextInputBehavior.js, packages/dropdown/src/behaviors/TextInputBehavior.test.js, packages/dropdown/src/presenters/InputPresenter.js, packages/dropdown/src/presenters/InputPresenter.test.js, packages/dropdown/src/presenters/__snapshots__/InputPresenter.test.js.snap
Issue: https://github.com/Autodesk/hig/issues/1073
Storybook: http://dreary-rub.surge.sh
Adds optional text entry to dropdown for custom filters and other functionality
To accomplish this, the following props are added to dropdown:
* **hasTextEntry** (bool): Enables user to focus and type into the dropdown text field
* **onTextEntryChange** (func): Called when user types into the dropdown text field
=> Add optional text entry to Dropdown

packages/dropdown/src/Dropdown.js
After making the change in https://github.com/Autodesk/hig/commit/c5b6975cd5e3b029efe387b430fb4e6b2a9dc38f, the development version of Dropdown produces an error
This branch resolves the error by adding a missing variable name
=> Dropdown: Correct variable names for Downshift onChange event

packages/dropdown/src/Dropdown.js
=> Revert "Dropdown: Correct variable names for Downshift onChange event"

packages/label/src/Label.js, packages/label/src/Label.test.js, packages/label/src/__snapshots__/Label.test.js.snap, packages/label/src/__stories__/Label.stories.js, packages/label/src/__stories__/getKnobs.js, packages/label/src/__stories__/stories.js, packages/label/src/__stories__/withThemeProvider.js, packages/label/src/index.test.js
Issue: https://github.com/Autodesk/hig/issues/1078
Requires: https://github.com/Autodesk/hig/pull/1154
Adds Storybook, VR and markup snapshot tests for the Label component.  Ensures that referencing form elements is working by testing the `form` and `htmlFor` props.
=> Comprehensive tests for Label

packages/button/src/Button.js, packages/button/src/Button.test.js, packages/button/src/__stories__/getKnobs.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/presenters/__snapshots__/FlyoutPresenter.test.js.snap
Story: https://github.com/Autodesk/hig/issues/1177
Flyout has an `onHover` event that utilizes `onMouseEnter`, however there is no equivalent `onMouseLeave`.  Both events will be needed to enable Tooltip's hover functionality.  
This branch adds `onMouseEnter` and `onMouseLeave` to Button.  
It preserves the existing `onHover` for backwards compatibility.  If both `onHover` and `onMouseOver` are provided, both will be triggered
=> Add onMouseEnter, onMouseLeave events to Button

packages/modal/package.json, packages/modal/src/Modal.test.js, packages/modal/src/__snapshots__/Modal.test.js.snap, packages/modal/src/presenters/ModalHeaderPresenter.js, packages/modal/src/presenters/ModalPresenter.js, packages/modal/src/presenters/__snapshots__/ModalHeaderPresenter.test.js.snap, packages/modal/src/presenters/__snapshots__/ModalPresenter.test.js.snap
The `ModalPresenter` was displaying a warning about rendering nested `<a>` elements. This fixes the warning and improves the component's overall accessibility.
https://www.w3.org/WAI/GL/wiki/Using_ARIA_role%3Ddialog_to_implement_a_modal_dialog_box
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role
https://getbootstrap.com/docs/4.0/components/modal/#modal-components
=> Fix: correct modal a11y

packages/modal/package.json, packages/modal/src/presenters/ModalHeaderPresenter.js, packages/notifications-toast/src/NotificationsToast.js, packages/tooltip/src/Tooltip.js
* Fix dependency issues with `@hig/tooltip`, `@hig/modal`, and `@hig/notifications-toast`
* ~I found unexpected behavior in testing `@hig/notifications-toast`, so I'm putting it on pre-release until the issue is resolved.~
=> Fix: fix missing dependencies

packages/checkbox/src/behaviors/CheckboxBehavior.js, packages/checkbox/src/behaviors/CheckboxBehavior.test.js, packages/slider/src/Slider.js, packages/slider/src/Slider.test.js, packages/text-field/src/behaviors/TextInputBehavior.js, packages/text-field/src/behaviors/TextInputBehavior.test.js
When the `Checkbox`, `Slider`, and `TextField` are used as controlled components, the given `onChange` handlers will now be called when the components are interacted with.
=> Fix: call `onChange` handlers when controlled

packages/input/package.json, packages/input/src/__gemini__/Input.stories-test.js, packages/input/src/presenters/InputHaloPresenter.js, packages/input/src/presenters/InputPresenter.js, packages/label/package.json, packages/label/src/Label.js, packages/label/src/__stories__/infoOptions.js, packages/skeleton-item/package.json, packages/skeleton-item/src/SkeletonItem.js, packages/storybook/package.json, packages/themes/package.json, yarn.lock
Gemini tests for themed components (input, label, skeleton-item) seem to be failing. Yarn is installing the older version of `@hig/themes` and not installing the newest version for components that need it so temporarily changing the `@hig/themes` package name to be `@hig-themes-poc`. This allows packages using to grab the older `@hig/themes` package to grab from NPM, and components that need the new one to get it locally from the renamed package, the newest update is still in pre-release.
The renaming should go away when https://github.com/Autodesk/hig/issues/1207 is resolved.
=> chore: update themes version in theme-data components

packages/notifications-flyout/src/Notification.js, packages/notifications-flyout/src/NotificationsFlyout.js, packages/notifications-flyout/src/NotificationsFlyout.test.js, packages/notifications-flyout/src/__fixtures__/createSampleNotifications.js, packages/notifications-flyout/src/behaviors/NotificationBehavior.js
Call `onDismiss` by combining event handlers and add missing test coverage.
Addresses #1244
=> Fix: call `onDismiss` when notifications are dismissed

packages/eslint-config/package.json, packages/project-account-switcher/src/__gemini__/ProjectAccountSwitcherPresenter.gemini.js, packages/project-account-switcher/src/__snapshots__/ProjectAccountSwitcher.test.js.snap, packages/project-account-switcher/src/presenters/ProjectAccountSwitcherPresenter.js, packages/project-account-switcher/src/presenters/ProjectAccountSwitcherPresenter.test.js, packages/project-account-switcher/src/presenters/__snapshots__/ProjectAccountSwitcherPresenter.test.js.snap, yarn.lock
> This is a feature branch PR working towards the removal of legacy packages. It is expected that this branch will fail CI.
Adds missing keyboard interactions to project account switcher actions for improved a11y.
Contributes to #1208
=> Fix: add missing keyboard interactions to ProjectAccountSwitcher

.circleci/config.yml, packages/storybook/package.json, packages/storybook/scripts/storybookDomain.sh
CI builds were failing for branches created by Greenkeeper. This was due to invalid subdomains being generated for the branch storybooks.
Resolves #1299
=> chore(storybook): improve dynamic storybook domain generation

packages/input/src/presenters/__snapshots__/InputHaloPresenter.test.js.snap, packages/theme-context/src/ThemeContext/BaseContext.js, packages/theme-context/src/ThemeContext/Consumer.js, packages/theme-context/src/ThemeContext/ThemeContext.test.js
This changes the ThemeContext default to WebLight to be inline with the
legacy theme styling that many HIG consumers start with.
=> BREAKING: chg default HIGLightGray -> WebLight

packages/theme-data/src/baseTheme/system/colorScheme.js, packages/theme-data/src/basics/colors.js, packages/theme-data/src/colorSchemes/darkBlue/system/colorScheme.js, packages/theme-data/src/colorSchemes/lightGray/system/colorScheme.js
Resolves #1369 
1. `yarn build` at project root
1. run storybook and see that...
a. ...under Theme data > Color scheme that `colorScheme.iconColor` is defined and that you can switch the knob between light gray and dark blue
b. ...under Theme data > Basics - Colors that `basics.colors.iconLightGrayColor`, `basics.colors.iconDarkBlueColor`, `basics.colors.iconDarkGrayColor` are defined
=> Theme data for icons

packages/dropdown/src/presenters/InputPresenter.js, packages/notifications-toast/src/NotificationsToast.js, yarn.lock
also removes leftover `icon` css dependencies.
=> chore: fix yarn lock after greenkeeper dependency update

packages/avatar/src/__stories__/renderStory.js, packages/button/src/__stories__/renderStory.js, packages/flyout/src/__stories__/renderStory.js, packages/input/src/__stories__/renderStory.js, packages/label/src/__stories__/withThemeProvider.js, packages/skeleton-item/src/__stories__/renderStory.js, packages/spacer/src/__stories__/renderStory.js, packages/storybook/storybook-support/decorators/KnobbedThemeProvider.js, packages/theme-data/src/__stories__/ThemeData.stories.js
Resolves: https://github.com/Autodesk/hig/issues/1449. Now in `storybook` if you just use `KnobbedThemeProvider` without a `supportedThemes` prop then it will by default show web light, dark blue, light gray, and dark gray. If you want it to show only certain themes or a custom theme, then you would supply them through the `supportedThemes` prop like before.
=> chore: storybook knobbed theme provider default is all 4 themes

packages/typography/package.json, packages/typography/src/Typography.js, packages/typography/src/Typography.test.js, packages/typography/src/__snapshots__/Typography.test.js.snap
This PR is related to https://github.com/Autodesk/hig/pull/1466, which got merged into this branch (after [another PR](https://github.com/Autodesk/hig/pull/1453) on this branch was closed) instead of development. 
‼️ Note that until we clear up how alpha versioning works while rolling out breaking changes, I wasn't super clear about what to version this as in package.json. We may need to adjust that before merging.
If there is a semantic element that matches the variant provided, use
that semantic element instead of resolving all <Typography> components
to a single type of element. Also, this changes the default element type
from `<span>` to `<p>`.
Migrating from 1.0.0 to 2.0.0
If you need the same behavior that the default <span> provided before,
you can pass in custom styles to achieve …
=> Use semantic typography retry

packages/avatar/package.json
Avatar 1.0.0 was previously published and unpublished. This resulted in
NPM rejecting the latest attempt to release 1.0.0. This commit is an
attempt to trigger semantic release to bump the version to 1.0.1 so
that NPM accepts a new published version.
=> fix: resolve versioning issue, Avatar 0.2.0->1.0.0

packages/typography/package.json
Once this commit makes it to master, semantic release on CI will bump the version to 1.0.0 and publish the new package version. After the new package version is published, Greenkeeper will notify us about which consuming HIG packages could be updated by opening PRs. We will want to update those packages 1-by-1 as we make their components themable.
=> Release new Typography API

packages/typography/package.json
This is a change from 0.1.6 -> 1.0.0 so that HIG packages don't pull in the breaking changes from Typography and CI development can pass.
=> chore: manually bump Typography version to 1.0.0

packages/theme-context/package.json
When we initially merged the work to change the default theme from LightGray to WebLight, the commit message wasn't formatted to properly trigger a major version bump with semantic-release and was not published to NPM. This resolves that.
=> Release chg default theme LightGray -> WebLight

packages/components/package.json, packages/flyout/package.json, packages/flyout/src/Flyout.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/presenters/FlyoutPresenter.js, packages/flyout/src/presenters/FlyoutPresenter.test.js, packages/flyout/src/presenters/__snapshots__/FlyoutPresenter.test.js.snap, packages/flyout/src/presenters/stylesheet.js, packages/tooltip/src/Tooltip.test.js, yarn.lock
BREAKING CHANGE: The padding of the flyout container is 12px across all densities
The above breaking change note is to get semantic versioning to bump this package to `1.0.0` but I do not believe anyone is using density specific themes at the moment, but also manually updating the `package.json` so the dependent components do not pull this in yet.
With the padding no longer being density based, the `Flyout` no longer needs to do calculations on the `componentDidUpdate` life-cycle, so am undoing/reverting this commit:
https://github.com/Autodesk/hig/commit/e75cfb16fc4aa73eff5bfbd2c0398d8565bc2062#diff-32db5e56e9aa91b678c74a66f0c626d2
Resolves https://github.com/Autodesk/hig/issues/1537.
=> fix: remove padding based on density spacing

.circleci/config.yml, packages/storybook/package.json, yarn.lock
This adds `{{ .Revision }}` to the cache key for the dependency hash creation step in the CI jobs that run at the start of each workflow. This means that the dependency caching will only be fresh for the duration of the workflow/just this git commit. It allows all of the following steps of the workflow to use that cache and lets each CI build based on that same commit use the cache. Builds based on other commits will use their own cache.
=> Fine tune CI dependency caching

packages/theme-data/src/baseTheme/components/textLink.js, packages/theme-data/src/baseTheme/unresolvedRoles.js, packages/theme-data/src/basics/colors.js, packages/theme-data/src/colorSchemes/darkBlue/components/textLink.js, packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js, packages/theme-data/src/colorSchemes/webLight/components/_oldColors.js, packages/theme-data/src/colorSchemes/webLight/components/textLink.js, packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
as a developer
I can have theme data describing a text link
so I can build one that adheres to HIG design specs
=> feat: add theme data for text link

packages/typography/package.json, packages/typography/src/__stories__/Typography.stories.js, packages/typography/src/index.js
This import was previously used to get fonts. Recently, we replaced the
need for this with the use of the @hig/fonts packages, which consumers
should import alongside importing @hig/typography in order to get the
fonts.
=> Typography shopkeeping

packages/modal/README.md
Modal README was incorrectly suggesting the buttons prop which is
misleading.
=> docs: remove buttons prop for Modal

packages/avatar/package.json, packages/banner/package.json, packages/button/package.json, packages/checkbox/package.json, packages/dropdown/package.json, packages/flyout/package.json, packages/icon-button/package.json, packages/icons/package.json, packages/input/package.json, packages/label/package.json, packages/modal/package.json, packages/profile-flyout/package.json, packages/progress-bar/package.json, packages/progress-ring/package.json, packages/project-account-switcher/package.json, packages/radio-button/package.json, packages/side-nav/package.json, packages/skeleton-item/package.json, packages/slider/package.json, packages/spacer/package.json, packages/storybook/package.json, packages/surface/package.json, packages/tabs/package.json, packages/text-area/package.json, packages/text-link/package.json, packages/theme-data/package.json, packages/timestamp/package.json, packages/tooltip/package.json, packages/top-nav/package.json, packages/typography/package.json
Resolves https://github.com/Autodesk/hig/issues/1659.
- Moved `rich-text` out of `devDependencies` for all the components and instead added it as a `dependency` for `storybook`.
=> docs: move rich-text dependency out of comps into storybook

packages/side-nav/package.json
BREAKING CHANGE:
* CSS stylesheets no longer used
This commit is to allow for the proper `BREAKING CHANGE:` commit message so semantic release will properly version the component
=> feat: make side-nav themeable

packages/theme-data/src/basics/colors.js
Resolves: https://github.com/Autodesk/hig/issues/1976
=> fix: use correct color for dark themed icon colors

packages/input/src/presenters/InputHaloPresenter.stylesheet.js
The `Input` halo was grey when you had both `focus` and `hover`.
As far as I can tell this isn't correct. The HIG page seems to imply that on focus you should always have the blue halo.
The logic is ordered so that on hover it will return early from the function and apply the hover styles, missing the `hasFocus` section completely.
Change the logic of the function so that `focus` is considered before `hover` .
TODO (waiting on credentials)
=> Fix: Prioritize focus over hover behavior for Input halo

packages/dropdown/src/Dropdown.js, packages/dropdown/src/__stories__/getKnobs.js
After `Input` got the `error` prop, enable passing this prop from `Dropdown` to its inside `Input` component. Resolves the issue in https://github.com/Autodesk/hig/issues/2019
=> feat: add error prop for Dropdown

packages/flyout/README.md, packages/flyout/src/Flyout.js, packages/flyout/src/Flyout.test.js, packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/presenters/FlyoutPresenter.js, packages/flyout/src/presenters/PanelContainerPresenter.js, packages/flyout/src/presenters/PanelPresenter.js, packages/flyout/src/presenters/PointerPresenter.js, packages/flyout/src/presenters/PointerWrapperPresenter.js, packages/flyout/src/presenters/stylesheet.js
- Not like what we did for input, textarea, for Flyout (and the new Accordion, new Menu components) I added the logic of `if (customStylesheet) {...} else {...}` in `stylesheet.js`, the `stylesheet` actually is a prop like other props, so in each presenter.js, we just need to pass `stylesheet: customStylesheet` to our component's stylesheet function along with the other props, and then we will not need to add the `if else` logic again and again.
- I have tested it and also updated the README and jest files.
=> feat: add stylesheet prop to flyout

packages/avatar/README.md, packages/avatar/package.json, packages/avatar/src/Avatar.js, packages/avatar/src/Avatar.test.js, packages/avatar/src/__snapshots__/Avatar.test.js.snap
As we've done for other components, this PR is to allow className to be passed down to Avatar. This is a need for new Menu component, to add styles for menuItems contain avatars. otherwise we will have to add an additional wrapper for avatar.
=> feat: allow className to be passed to Avatar

packages/theme-data/README.md
Updating the read me for theme data to use the theme.json file rather than the resolvedRoles.json which doesn't contain both the meta data and the styles.
This would fix github issue #2048 (filed by me)
=> docs: Update theme data readme json section

packages/dropdown/README.md, packages/dropdown/src/Dropdown.js, packages/dropdown/src/__snapshots__/Dropdown.test.js.snap, packages/dropdown/src/__stories__/getKnobs.js, packages/dropdown/src/presenters/OptionPresenter.js, packages/dropdown/src/presenters/OptionPresenter.stylesheet.js, packages/dropdown/src/presenters/__snapshots__/OptionPresenter.test.js.snap, packages/dropdown/src/presenters/renderOptions.js
*  allow custom rendered options using the renderOption prop to have some of the built in dropdown/option functionality by passing in itemProps to the function
Resolves: https://github.com/Autodesk/hig/issues/2062
Resolves: https://github.com/Autodesk/hig/issues/2061
=> feat: allow for disabled options

packages/tabs/src/Tabs.js
fix https://github.com/Autodesk/hig/issues/2064
=> fix: tab with zero index not trigger to active in Tabs

packages/top-nav/src/presenters/stylesheet.js
Changed -ms-overflow-style to be msOverflowStyle to prevent an error message when using interactions. Also updated the branch name example in the contributing guide to reflect that a change in docs is not a fix which confused me last time. :)
No breaking changes.
=> fix: Updated stylesheet to use camelCase for top nav component

packages/icons/README.md
👋 Hello! Found a typo in the docs for the @hig/icons package.
=> docs: fix @hig/icons SVG source file path in docs

packages/avatar/src/Avatar.js
Fix the problem that function initialsFromName() can't handle some non-English names properly, for example: "Λεωνίδας ωή", "Иван Виктор" and "安倍晋三".
=> fix: function initialsFromName() can't handle some non-English names properly

packages/multi-downshift/src/MultiDownshift.js
BREAKING CHANGE:
initialSelectedItems was returning the correct default items but was not being used, using this instead of defaultSelectedItems which was always returning empty and now is a redundancy and therefore has been remove.
=> fix: defaultSelectedItems prop not working

packages/project-account-switcher/src/presenters/constructPlaceholder.js
Fix issue #2332: ProjectAccountSwitcher does not accept non-English labels.
https://github.com/Autodesk/hig/issues/2332
=> fix: ProjectAccountSwitcher does not accept non-English labels

packages/project-account-switcher/src/presenters/constructPlaceholder.js
Regex lookbehind is not supported in IE and Safari
=> fix: don't use regex lookbehind, revert to previous regex

packages/avatar/src/Avatar.js, packages/avatar/src/Avatar.stylesheet.js, packages/avatar/src/constants.js, packages/avatar/src/index.js
**This PR must be merged before Avatar Bundle PR https://github.com/Autodesk/hig/pull/2432**
- Some linting changes to remove the `// eslint-disable-next-line react/prop-types, prettier/prettier` comments and more throughly describe prop types.
- New use of StyleItems values.
- These changes are part of the Avatar Bundle work described in https://jira.autodesk.com/browse/ACWB-8852.
See Figma spec here:
https://www.figma.com/file/S657OgrT8eiU4TreWWYQi8/LIB_Components?node-id=528%3A15
Another commit with the Avatar Bundle component updates that utilize `StyleItems` will follow this one.
=> feat(avatar): Small refactors for usage by avatarBundle (ACWB-8852)

packages/theme-data/src/baseTheme/system/colorScheme.js, packages/theme-data/src/colorSchemes/darkBlue/system/colorScheme.js
Reverts Autodesk/hig#2485 I need re run the tests to update them for this to pass
=> Revert "fix: set success color for light gray to correct value"

packages/menu/src/Option.js, packages/menu/src/Option.test.js, packages/menu/src/presenters/OptionPresenter.js
Adds a ref to the Option component of Menu,
so consumers are able to get a reference to the internal 'li' element
(Test was copied from https://github.com/Autodesk/hig/pull/2260 - couldn't think of a better way to do it)
=> feat(menu): Add optionRef to Option component

.circleci/config.yml, DEVELOPING.md, yarn.lock
This will support node v12. I verified node v10 also still works (at least `yarn build`), though I don't think we should officially state v10 support in the DEVELOPING.md file since v10 is end-of-life.
For node 14, it appears that gemini (and perhaps other packages) will need a major version bump to gemini@^6.
=> update some dependencies to support node 12

packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/notifications-flyout/src/presenters/stylesheet.js, packages/notifications-toast/src/NotificationsToast.stylesheet.js
This issue affects notifications related to Electron custom 3D model workflow
which might contain long 3D package name derived from IPC name
(E.g., STANDOFF_HEX_FEMALE_500X1200_M2.5X0.45_MTGP755H270.f3d).
=> fix: change Toast and Flyout notifications to wrap long words properly

packages/tree-view/src/TreeItem.js, packages/tree-view/src/TreeView.js, packages/tree-view/src/__fixtures__/sampleTreeNodeObject.js, packages/tree-view/src/__snapshots__/TreeView.test.js.snap, packages/tree-view/src/__stories__/stories.js, packages/tree-view/src/behaviors/TreeItemBehavior.js, packages/tree-view/src/behaviors/TreeItemBehavior.test.js, packages/tree-view/src/behaviors/TreeViewBehavior.js, packages/tree-view/src/presenters/fileview/TreeObjectNestedSubTreeItem.js, packages/tree-view/src/presenters/fileview/TreeObjectNestedSubTreeItem.test.js, packages/tree-view/src/presenters/fileview/TreeObjectSubTreeItem.js, packages/tree-view/src/presenters/fileview/__snapshots__/TreeObjectNestedSubTreeItem.test.js.snap, packages/tree-view/src/presenters/fileview/__snapshots__/TreeObjectView.test.js.snap
The function is quite the same as clicking on the operator icon, but easier to operate for end users. 
- Add property `expandByDoubleClick` to component `TreeItem` as an optional one and default value is false.
- Add meta property `expandByDoubleClick` to tree node object.
- Add a new storybook entry of treeview to present the function.
A video to show the function:
https://user-images.githubusercontent.com/37433962/150101817-969e2d95-3236-4fd2-8a9f-85b5398ea2e2.mp4
=> feat(dblClick): double click to expand or collapse tree item

packages/top-nav/package.json
There is a problem with the version number of the avatar component in the package.json of the tov-nav component. This is probably the source of the problems with theme-context, because the avatar component with version 2.0.0 works with theme-context 3.0.3. The current version of the theme-context is 4.1.0 and the avatar is 2.1.0. The version of create-react-context 0.3.0 has been the same in previous versions of theme-context.
https://jira.autodesk.com/browse/HIG1-32
=> fix: update number version of avatar dependencie of top-nav component. Issue HIG1-32

packages/tree-view/src/TreeItem.test.js, packages/tree-view/src/__snapshots__/TreeView.test.js.snap, packages/tree-view/src/__stories__/stories.js, packages/tree-view/src/presenters/SubTreeViewCombined.js, packages/tree-view/src/presenters/TreeItemPresenter.js, packages/tree-view/src/presenters/TreeViewPresenter.js
- @hig/tree-view can only accept a TreeItem as child(ren). This PR is to make it be able to accept a high order component or function component wrapped TreeItem. 
- add unit test and storybook
=> feat(HOC): TreeView can contain high order component of TreeItem

packages/menu/src/__snapshots__/Option.test.js.snap, packages/theme-data/src/baseTheme/components/menu.js
Added .5 transform to menu.header.fontColor role to match what's in the Figma files
=> fix: set transform on menu header to correct value

packages/tree-view/src/TreeItem.js, packages/tree-view/src/TreeItem.test.js, packages/tree-view/src/TreeView.js, packages/tree-view/src/presenters/SingleTreeNodeFolderPresenter.js, packages/tree-view/src/presenters/SingleTreeNodePresenter.js
- As the TreeItem is a function component, it can't support assigning a `ref` directly. In this change, a normal property named `itemRef` is used to forward and pass the ref object to the descendants HTML element of the TreeItem.
- update the unit test
- The screenshot is a sample of using a 3rd party component [react-dnd](https://github.com/react-dnd/react-dnd) which needs to assign a ref to the TreeItem to drag and drop.
- only support ref in the `children` render method. The TreeNode object render doesn't support ref now.
=> feat(TreeView): Make TreeItem support 'ref' property

packages/numeric-input/src/behaviors/SpinnerBehavior.js
A user found a bug in the "numeric input" component, the "onChange" event fires when you click the up and down arrows of the component, but the event is not fired when you manually type a value, you can replicate the bug in the storybook using the ACTION LOGGER.
[Storybook - Numeric Input](http://storybook.hig.autodesk.com/?knob-Step=1&knob-Options=%5B%22HIG%20Light%20Theme%22%2C%22HIG%20Dark%20Blue%20Theme%22%2C%22Matrix%20Theme%22%5D&knob-Alignment=left&knob-Density=medium-density&knob-Font%20Weight=normal&knob-Required=&knob-Children=This%20should%20render%20nicely.&knob-Color%20scheme=hig-light-gray&knob-Value=&knob-Placeholder=Select%20a%20theme&knob-Label=Foo&selectedKind=Forms%7CNumericInput&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions% …
=> fix: Fixing a bug in numeric input component

packages/slider/src/__snapshots__/Slider.test.js.snap, packages/slider/src/presenters/__snapshots__/SliderPresenter.test.js.snap, packages/slider/src/presenters/stylesheet.js, packages/slider/src/presenters/stylesheet.test.js
[BUG] Slider is transparent when disabled in Firefox:
PR repo: https://github.com/Autodesk/hig/issues/2621
PR board HIG 1.0: https://jira.autodesk.com/browse/HIG1-39
=> fix: Fixing slider component bug, transparency in Firefox

packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap, packages/rich-text/src/__snapshots__/RichText.test.js.snap, packages/rich-text/src/stylesheet.js
- The bottom margin value in the rich-text component was set to 0 in the stylesheet file. 
- The RichText snapshot test was updated. 
-  The Notification Flyout snapshot tests were updated.
Ticket repo: https://github.com/Autodesk/hig/issues/2468
Ticket board HIG 1.0: https://jira.autodesk.com/browse/HIG1-34
**Screenshots**
**Before:**
**After:**
=> fix:  Bottom margin Rich text component

packages/flyout/src/__snapshots__/Flyout.test.js.snap, packages/flyout/src/presenters/__snapshots__/FlyoutPresenter.test.js.snap, packages/flyout/src/presenters/stylesheet.js, packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap, packages/profile-flyout/src/__snapshots__/ProfileFlyout.test.js.snap, packages/project-account-switcher/src/__snapshots__/ProjectAccountSwitcher.test.js.snap, packages/tooltip/src/__snapshots__/Tooltip.test.js.snap
[BUG] Fixing flyout component bug, extra space on the right:
PR repo: https://github.com/Autodesk/hig/issues/2516
PR board HIG 1.0: https://jira.autodesk.com/browse/HIG1-38
The error was found in the "tooltip" component but it comes from the "flyout" component because "tooltip" consumes "flyout". We had extra space on the right that was fixed by removing the fixed width of 100%.
In addition, another commit was created to fix the snapshots tests of other components.
=> fix: Fixing flyout component bug, extra space on the right

packages/text-link/src/TextLink.js
Here is the console error:
Warning: Invalid value for prop 'stylesheet' on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM
Just implement what David Becroft suggested in the issue 2626.
=> Fix console error of text-link for issue 2626, no way to UT this

packages/text-area/src/TextArea.js, packages/text-area/src/__snapshots__/TextArea.test.js.snap
After React17 upgrade of HIG TextArea component, textareaStylesheet callback is missing one parameter because of which the styles in the textarea are getting some undefined values
Before:
After:
=> fix: Sending correct parameters in the textareaStylesheet callback function of TextArea component

packages/fonts/README.md
BREAKING CHANGE: Fonts are pointing to a new cdn
=> docs: update font imports

packages/top-nav/src/presenters/__snapshots__/TopNavPresenter.test.js.snap, packages/top-nav/src/presenters/stylesheet.js
This issue affects Top-Nav related to updating stylesheet (remove lineHeight)
Issue: https://github.com/Autodesk/hig/issues/2226
=> fix: remove lineHeight in topNavLogoWrapper
